force-app/main/default/objects/Case_Type__c/Case_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Type__c/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <label>Claim</label>
</RecordType>

force-app/main/default/objects/Claim_Header__c/Claim_Header__c.object-meta.xml
<CustomObject>
    <label>Claim Header</label>
    <nameField>
        <displayFormat>CLH-{0000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Header__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Headers</relationshipLabel>
    <relationshipName>Claim_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>L1 Approved</fullName>
            </value>
            <value>
                <fullName>L2 Approved</fullName>
            </value>
            <value>
                <fullName>L3 Approved</fullName>
            </value>
            <value>
                <fullName>L4 Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Header__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimHeaderControllerTest.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : ClaimHeaderControllerTest
 * Author          : <YourName>
 * Created Date    : Mar 23, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Mar 23, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Mar 23, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

@isTest
public class ClaimHeaderControllerTest {

    @testSetup
    static void setupData() {
          Id accrt = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Distributor').getRecordTypeId();

        // Create Active Account
        Account acc = new Account(
            Name = 'Test Distributor',
            Code__c = 'ACC001',
            Status__c = 'Active',
             RecordTypeId = accrt
        );
        insert acc;
        
        Account accTest = new Account(
            Name = 'Test Distributor1',
            Code__c = 'ACC002',
            Status__c = 'Active',
             RecordTypeId = accrt
        );
        insert accTest;

        // Create Case Type RecordType
        Id rt = Schema.SObjectType.Case_Type__c.getRecordTypeInfosByDeveloperName().get('Claim').getRecordTypeId();

        // Create Case Type
        Case_Type__c ct = new Case_Type__c(
            Name = 'Test Claim Type',
            RecordTypeId = rt,
            Active__c = true
            
        );
        insert ct;
        
        

        // Create a user (non-portal)
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@hangyo.com',
            Username = 'testuser' + DateTime.now().getTime() + '@test.com',
            Alias = 'tstusr',
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = p.Id
        );
        insert u;
    }

    @isTest
    static void testGetMultiplePicklistValues() {
        Test.startTest();
        Map<String, List<getPicklistHelper.PicklistOption>> res = ClaimHeaderController.getMultiplePicklistValues();
        Test.stopTest();
    }

    @isTest
    static void testGetAccountsAndCaseTypesMap() {
        Test.startTest();
        Map<String, List<Object>> res = ClaimHeaderController.getAccountsAndCaseTypesMap();
        Test.stopTest();
    }

    @isTest
    static void testCreateClaimWithAttachment_success() {
        // Prepare Base64 file
        Blob bodyBlob = Blob.valueOf('Test File');
        String base64Data = EncodingUtil.base64Encode(bodyBlob);

        // Build request data
        Map<String, Object> header = new Map<String, Object>{
            'distributorId' => [SELECT Id FROM Account Where Name = 'Test Distributor' LIMIT 1 ].Id,
            'claimMonth' => 'March',
            'claimYear' => '2025',
            'claimDescription' => 'Test claim desc',
            'submittedDate' => String.valueOf(Date.today()),
            'claimStatus' => 'Draft'
        };

        List<Object> lines = new List<Object>();
        lines.add(new Map<String, Object>{
            'lineId' => 'frontend-1',
            'caseTypeId' => [SELECT Id FROM Case_Type__c LIMIT 1 ].Id,
            'amount' => '1000',
            'date' => String.valueOf(Date.today()),
            'remarks' => 'Test remark',
            'files' => new List<Object>{
                new Map<String,Object>{
                    'base64' => base64Data,
                    'name' => 'testFile.txt'
                }
            }
        });

        Map<String, Object> request = new Map<String, Object>{
            'header' => header,
            'lines' => lines
        };

        Test.startTest();
        Map<String,String> response = ClaimHeaderController.createClaimWithAttachment(JSON.serialize(request));
        Test.stopTest();

       
    }
    @isTest
    static void testCreateClaimWithAttachment_success1() {
        // Prepare Base64 file
        Blob bodyBlob = Blob.valueOf('Test File');
        String base64Data = EncodingUtil.base64Encode(bodyBlob);
        
     Account acc = [SELECT Id, Name FROM Account Where Name = 'Test Distributor1' LIMIT 1];
        Claim_Header__c ch = new Claim_Header__c(
            Distributor__c = acc.Id,
            Month__c = 'March',
            Year__c = '2025',
            Status__c = 'Draft'
        );
        insert ch;
        // Build request data
        Map<String, Object> header = new Map<String, Object>{
            'distributorId' => acc.Id,
            'claimMonth' => 'March',
            'claimYear' => '2025',
            'claimDescription' => 'Test claim desc',
            'submittedDate' => String.valueOf(Date.today()),
            'claimStatus' => 'Draft'
        };

        List<Object> lines = new List<Object>();
        lines.add(new Map<String, Object>{
            'lineId' => 'frontend-1',
            'caseTypeId' => [SELECT Id FROM Case_Type__c LIMIT 1 ].Id,
            'amount' => '1000',
            'date' => String.valueOf(Date.today()),
            'remarks' => 'Test remark',
            'files' => new List<Object>{
                new Map<String,Object>{
                    'base64' => base64Data,
                    'name' => 'testFile.txt'
                }
            }
        });
        
        Map<String, Object> request = new Map<String, Object>{
            'header' => header,
            'lines' => lines
        };

        Test.startTest();
        Map<String,String> response = ClaimHeaderController.createClaimWithAttachment(JSON.serialize(request));
        Test.stopTest();

       
    }

    @isTest
    static void testCreateClaimWithAttachment_success2() {
        // Prepare Base64 file
        Blob bodyBlob = Blob.valueOf('Test File');
        String base64Data = EncodingUtil.base64Encode(bodyBlob);
        
     Account acc = [SELECT Id, Name FROM Account Where Name = 'Test Distributor1' LIMIT 1];
        Claim_Header__c ch = new Claim_Header__c(
            Distributor__c = acc.Id,
            Month__c = 'March',
            Year__c = '2025',
            Status__c = 'Approved'
        );
        insert ch;
        // Build request data
        Map<String, Object> header = new Map<String, Object>{
            'distributorId' => acc.Id,
            'claimMonth' => 'March',
            'claimYear' => '2025',
            'claimDescription' => 'Test claim desc',
            'submittedDate' => String.valueOf(Date.today()),
            'claimStatus' => 'Draft'
        };

        List<Object> lines = new List<Object>();
        lines.add(new Map<String, Object>{
            'lineId' => 'frontend-1',
            'caseTypeId' => [SELECT Id FROM Case_Type__c LIMIT 1 ].Id,
            'amount' => '1000',
            'date' => String.valueOf(Date.today()),
            'remarks' => 'Test remark',
            'files' => new List<Object>{
                new Map<String,Object>{
                    'base64' => base64Data,
                    'name' => 'testFile.txt'
                }
            }
        });
        
        Map<String, Object> request = new Map<String, Object>{
            'header' => header,
            'lines' => lines
        };

        Test.startTest();
        Map<String,String> response = ClaimHeaderController.createClaimWithAttachment(JSON.serialize(request));
        Test.stopTest();

       
    }

    @isTest
    static void testCreateClaimWithAttachment_error() {
        // Invalid request (missing caseTypeId and files)
        Map<String, Object> header = new Map<String, Object>{
            'distributorId' => [SELECT Id FROM Account LIMIT 1].Id,
            'claimMonth' => 'March',
            'claimYear' => '2025',
            'claimDescription' => 'Invalid claim',
            'claimStatus' => 'Draft'
        };

        List<Object> lines = new List<Object>();
        lines.add(new Map<String, Object>{
            'lineId' => 'frontend-2',
            'amount' => '2000',
            'remarks' => 'Missing caseTypeId',
            'files' => new List<Object>() // Empty files
        });

        Map<String, Object> request = new Map<String, Object>{
            'header' => header,
            'lines' => lines
        };

        Test.startTest();
        Map<String,String> response = ClaimHeaderController.createClaimWithAttachment(JSON.serialize(request));
        Test.stopTest();

        
    }
    
    @isTest
static void testIsClaimHeaderApproved() {

    Account acc = [
        SELECT Id
        FROM Account
        WHERE Name = 'Test Distributor1'
        LIMIT 1
    ];

    Claim_Header__c ch = new Claim_Header__c(
        Distributor__c = acc.Id,
        Month__c = 'June',
        Year__c = '2025',
        Status__c = 'Approved'
    );
    insert ch;

    Test.startTest();
    Boolean result = ClaimHeaderController.isClaimHeaderApproved(
        acc.Id,
        'June',
        '2025'
    );
    Test.stopTest();

    System.assertEquals(true, result);
}
    
    
}