force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <referenceTo>Case_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Super Stockist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Distributor_Transfer_From__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Transfer_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor (Transfer From)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_type_Name__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Distributor (Transfer From))</relationshipLabel>
    <relationshipName>Cases7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Distributor_Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Transfer_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor (Transfer To)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_type_Name__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Distributor (Transfer To))</relationshipLabel>
    <relationshipName>Cases8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/New_Asset_Code__c.field-meta.xml
<CustomField>
    <fullName>New_Asset_Code__c</fullName>
    <label>New Asset Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/OEM_serial_number__c.field-meta.xml
<CustomField>
    <fullName>OEM_serial_number__c</fullName>
    <label>QR Code Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Old_Asset_Code__c.field-meta.xml
<CustomField>
    <fullName>Old_Asset_Code__c</fullName>
    <label>Old Asset Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Request_type__c.field-meta.xml
<CustomField>
    <fullName>Request_type__c</fullName>
    <label>Request type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_type_Name__c</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Retailer)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Retailer_Transfer_From__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Transfer_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer (Transfer From)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_type_Name__c</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Retailer (Transfer From))</relationshipLabel>
    <relationshipName>Cases9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Retailer_Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Transfer_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer (Transfer To)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_type_Name__c</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Retailer (Transfer To))</relationshipLabel>
    <relationshipName>Cases0jba</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Scrap__c.field-meta.xml
<CustomField>
    <fullName>Scrap__c</fullName>
    <label>Scrap</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transferred to warehouse</fullName>
            </value>
            <value>
                <fullName>Replacement Given</fullName>
                <isActive>false</isActive>
                <label>Replacement Given</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>L1 Approved</fullName>
            </value>
            <value>
                <fullName>L2 Approved</fullName>
            </value>
            <value>
                <fullName>L3 Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Installation Pending</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
                <isActive>false</isActive>
                <label>Pending for Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Type__c/Case_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AssetTransferQueueable.cls
public without sharing class AssetTransferQueueable implements Queueable {
    
    private Set<Id> caseIds;
    
    public AssetTransferQueueable(Set<Id> caseIds) {
        this.caseIds = caseIds;
    }
    
    public void execute(QueueableContext context) {
        try {
            List<Case__c> cases = [
                SELECT Id, Status__c, Case_Type__c, Case_Type__r.Name, OEM_serial_number__c,
                       Request_type__c, Retailer_Transfer_To__c,
                       Distributor_Transfer_To__c, Scrap__c,
                       Retailer_Transfer_From__c, Distributor_Transfer_From__c,
                       Sync__c, New_Asset_Code__c, Old_Asset_Code__c,
                       Serial_Number__c, Make__c, Model__c, Capacity__c,
                       Retailer__c, Distributor__c
                FROM Case__c
                WHERE Id IN :caseIds
                AND Sync__c = true
            ];
            
            if (!cases.isEmpty()) {
                CaseTriggerHandler.handleAfterUpdate(cases, new Map<Id, Case__c>());
                List<Case__c> casesToReset = new List<Case__c>();
                for (Case__c c : cases) {
                    casesToReset.add(new Case__c(Id = c.Id, Sync__c = false));
                }
                Database.update(casesToReset, AccessLevel.SYSTEM_MODE);
            }
        } catch (Exception e) {
            System.debug('AssetTransferQueueable error: ' + e.getMessage());
        }
    }
}