force-app/main/default/objects/Good_receipt_notes__c/Good_receipt_notes__c.object-meta.xml
<CustomObject>
    <label>Good receipt note</label>
    <nameField>
        <displayFormat>GRN-{0000}</displayFormat>
        <label>GRN Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Good receipt notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Good_receipt_notes__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Good receipt notes</relationshipLabel>
    <relationshipName>GRN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Good_receipt_notes__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Invoiced Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>IN - {0000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventorys</relationshipLabel>
    <relationshipName>Inventorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_in_hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_in_hand__c</fullName>
    <label>Quantity in hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Adjustment__c/Inventory_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Inventory Adjustment</label>
    <nameField>
        <displayFormat>Invadj - {0000}</displayFormat>
        <label>Inventory Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Adjustment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Adjustment__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipName>Inventory_Disturbances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Adjustment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory Adjustment</relationshipLabel>
    <relationshipName>Inventory_Adjustment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Increment</fullName>
            </value>
            <value>
                <fullName>Decrement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link Invoice records for an Order</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <isActive>false</isActive>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Sent</fullName>
                <isActive>false</isActive>
                <label>Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <description>To capture the Invoice Line Item&apos;s total quantity</description>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Invoice-Item-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture ordered Product</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>To capture the ordered Product Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>All_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Discount_Amount_Order__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount_Order__c</fullName>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Value__c</fullName>
    <label>Total Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Order</fullName>
            </value>
            <value>
                <fullName>Counter Order</fullName>
            </value>
            <value>
                <fullName>Under Super Stockist</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>Bulk Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>Order-Item-{0000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Ordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Quantity__c</fullName>
    <label>Ordered Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product To be deleted</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom product</description>
    <label>Products</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/RetailerCodeSetting__c/RetailerCodeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RetailerCodeSetting</label>
</CustomObject>

force-app/main/default/objects/RetailerCodeSetting__c/fields/Latest_Code__c.field-meta.xml
<CustomField>
    <fullName>Latest_Code__c</fullName>
    <label>Latest_Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateQuantityInHandTest.cls
@isTest
public class UpdateQuantityInHandTest {
    @isTest
    static void testGetOrderRecord() {
        RetailerCodeSetting__c setting = new RetailerCodeSetting__c(Name = 'SF', Latest_Code__c = 100);
        insert setting;
        
        Account acc = new Account(
            Name = 'Test Distributor',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Distributor' AND SObjectType = 'Account' LIMIT 1].Id,
            Phone = '123-456-7890'
        );
        insert acc;
        
        Product__c product1 = new Product__c(Name = 'Product 1', IsActive__c = true);
        Product__c product2 = new Product__c(Name = 'Product 2', IsActive__c = true);
        insert new List<Product__c>{product1, product2};
             
        Order__c primaryOrder = new Order__c(
            AccountId__c = acc.Id,
            EffectiveDate__c = Date.today(),
            Total_Quantity__c = 100,
            Total_Order_Value__c = 2000,
            Discount_Amount_Order__c = 200 ,
            Status__c = 'Delivered',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Counter Order' AND SObjectType = 'Order__c' LIMIT 1].Id
        );
        insert primaryOrder;
        
        // Create Order Line Items for the Order
        Order_Line_Item__c orderLine11 = new Order_Line_Item__c(
            Order__c = primaryOrder.Id,
            Products__c = product1.Id,
            Product_Price__c = 20,
            Ordered_Quantity__c = 50 
        );

        Order_Line_Item__c orderLine12 = new Order_Line_Item__c(
            Order__c = primaryOrder.Id,
            Products__c = product2.Id,
            Product_Price__c = 30,
            Ordered_Quantity__c = 50
        );
        insert new List<Order_Line_Item__c>{orderLine11, orderLine12};
        
        // Create inventory records for the products
        Inventory__c inv1 = new Inventory__c(Product__c = product1.Id, Quantity_in_hand__c = 100, Distributor_Name__c = acc.Id);
        insert inv1;
        
        Inventory__c inv2 = new Inventory__c(Product__c = product2.Id, Quantity_in_hand__c = 200, Distributor_Name__c = acc.Id);
        insert inv2;
        
        Map<Id, Order__c> oldOrderMap = new Map<Id, Order__c>();
        oldOrderMap.put(primaryOrder.Id, new Order__c(Status__c = 'Order Placed'));
        
        Test.startTest();
        UpdateQuantityInHand.getOrderRecord(new List<Order__c>{primaryOrder}, oldOrderMap);
        Test.stopTest();
        
        Inventory__c updatedInv1 = [SELECT Quantity_in_hand__c FROM Inventory__c WHERE Id = :inv1.Id];
        //Inventory__c updatedInv2 = [SELECT Quantity_in_hand__c FROM Inventory__c WHERE Id = :inv2.Id];
        
        System.assertEquals(50, updatedInv1.Quantity_in_hand__c, 'Quantity in hand for Product 1 should be updated');
        List<Inventory_Adjustment__c> inventoryAdjustments = [SELECT Quantity__c, Type__c, Primary_Related_transaction__c, Secondary_invoice__c FROM Inventory_Adjustment__c];
        
        System.assertEquals(2, inventoryAdjustments.size(), 'There should be two inventory adjustment records');
    }
    
    @isTest
    static void testUpdateSecondaryInvoiceQuantity(){
        Account acc = new Account(
            Name = 'Test Distributor',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Distributor' AND SObjectType = 'Account' LIMIT 1].Id,
            Phone = '123-456-7890'
        );
        insert acc;
        
        Product__c product1 = new Product__c(Name = 'Product 1', IsActive__c = true);
        Product__c product2 = new Product__c(Name = 'Product 2', IsActive__c = true);
        insert new List<Product__c>{product1, product2};
             
        Order__c secOrder = new Order__c(
            AccountId__c = acc.Id,
            EffectiveDate__c = Date.today(),
            Total_Quantity__c = 100,
            Total_Order_Value__c = 2000,
            Discount_Amount_Order__c = 200 ,
            Status__c = 'Order Placed',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Secondary Order' AND SObjectType = 'Order__c' LIMIT 1].Id
        );
        insert secOrder;
        
        // Create Order Line Items for the Order
        Order_Line_Item__c orderLine11 = new Order_Line_Item__c(
            Order__c = secOrder.Id,
            Products__c = product1.Id,
            Product_Price__c = 20,
            Ordered_Quantity__c = 50 
        );

        Order_Line_Item__c orderLine12 = new Order_Line_Item__c(
            Order__c = secOrder.Id,
            Products__c = product2.Id,
            Product_Price__c = 30,
            Ordered_Quantity__c = 50
        );
        insert new List<Order_Line_Item__c>{orderLine11, orderLine12};
        
        Invoice__c secInvoice = new Invoice__c(
            Name = 'INV0000900',
            Order__c = secOrder.Id,
            Distributor_Account__c = acc.Id,
            Invoice_Number__c = 'INV0000900',
            Total_Quantity__c = 100,
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Secondary Invoice' AND SObjectType = 'Invoice__c' LIMIT 1].Id ,
            Status__c = 'Confirmed'
        );
        insert secInvoice;
        
        // Create Order Line Items for the Order
        Invoice_Line_Item__c invoiceLine11 = new Invoice_Line_Item__c(
            Invoice__c = secInvoice.Id,
            Product__c = product1.Id,
            Quantity__c = 50 
        );

        Invoice_Line_Item__c invoiceLine12 = new Invoice_Line_Item__c(
            Invoice__c = secInvoice.Id,
            Product__c = product2.Id,
            Quantity__c = 50
        );
        insert new List<Invoice_Line_Item__c>{invoiceLine11, invoiceLine12};
        
        // Create inventory records for the products
        Inventory__c inv1 = new Inventory__c(Product__c = product1.Id, Quantity_in_hand__c = 100, Distributor_Name__c = acc.Id);
        insert inv1;
        
        Inventory__c inv2 = new Inventory__c(Product__c = product2.Id, Quantity_in_hand__c = 200, Distributor_Name__c = acc.Id);
        insert inv2;
        
        Map<Id, Invoice__c> oldOrderMap = new Map<Id, Invoice__c>();
        oldOrderMap.put(secInvoice.Id, new Invoice__c(Status__c = 'Draft'));
        
        Test.startTest();
        UpdateQuantityInHand.updateSecondaryInvoiceQuantity(new List<Invoice__c>{secInvoice}, oldOrderMap);
        Test.stopTest();
    }
    
    @isTest
    static void testupdatePrimaryInvoiceQuantity(){
        Account acc = new Account(
            Name = 'Test Distributor',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Distributor' AND SObjectType = 'Account' LIMIT 1].Id,
            Phone = '123-456-7890'
        );
        insert acc;
        
        Product__c product1 = new Product__c(Name = 'Product 1', IsActive__c = true);
        Product__c product2 = new Product__c(Name = 'Product 2', IsActive__c = true);
        insert new List<Product__c>{product1, product2};
             
        Order__c secOrder = new Order__c(
            AccountId__c = acc.Id,
            EffectiveDate__c = Date.today(),
            Total_Quantity__c = 100,
            Total_Order_Value__c = 2000,
            Discount_Amount_Order__c = 200 ,
            Status__c = 'Order Placed',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Secondary Order' AND SObjectType = 'Order__c' LIMIT 1].Id
        );
        insert secOrder;
        
        // Create Order Line Items for the Order
        Order_Line_Item__c orderLine11 = new Order_Line_Item__c(
            Order__c = secOrder.Id,
            Products__c = product1.Id,
            Product_Price__c = 20,
            Ordered_Quantity__c = 50 
        );

        Order_Line_Item__c orderLine12 = new Order_Line_Item__c(
            Order__c = secOrder.Id,
            Products__c = product2.Id,
            Product_Price__c = 30,
            Ordered_Quantity__c = 50
        );
        insert new List<Order_Line_Item__c>{orderLine11, orderLine12};
        
        Invoice__c secInvoice = new Invoice__c(
            Name = 'INV0000900',
            Order__c = secOrder.Id,
            Distributor_Account__c = acc.Id,
            Invoice_Number__c = 'INV0000900',
            Total_Quantity__c = 100,
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Primary Invoice' AND SObjectType = 'Invoice__c' LIMIT 1].Id ,
            Status__c = 'Confirmed'
        );
        insert secInvoice;
        
        // Create Order Line Items for the Order
        Invoice_Line_Item__c invoiceLine11 = new Invoice_Line_Item__c(
            Invoice__c = secInvoice.Id,
            Product__c = product1.Id,
            Quantity__c = 50
        );

        Invoice_Line_Item__c invoiceLine12 = new Invoice_Line_Item__c(
            Invoice__c = secInvoice.Id,
            Product__c = product2.Id,
            Quantity__c = 50
        );
        insert new List<Invoice_Line_Item__c>{invoiceLine11, invoiceLine12};
            
        Map<Id, Invoice_Line_Item__c> oldOrderMap = new Map<Id, Invoice_Line_Item__c>();
        oldOrderMap.put(invoiceLine11.Id , invoiceLine11);
        oldOrderMap.put(invoiceLine12.Id , invoiceLine12);
        
        Good_receipt_notes__c grn = new Good_receipt_notes__c(
            Total_Changed_Quantity__c = 50,
            Total_Quantity__c = 100 ,
            Order__c = secOrder.Id,
            Invoice__c = secInvoice.Id
        );
        insert grn;
        
        Invoice_Line_Item__c updateInvoiceLine11 = new Invoice_Line_Item__c(
            Id = invoiceLine11.Id , 
            Received_Quantity__c = 25,
            Good_receipt_note__c = grn.Id
        );

        Invoice_Line_Item__c updateInvoiceLine12 = new Invoice_Line_Item__c(
            Id = invoiceLine12.Id , 
            Received_Quantity__c = 25,
            Good_receipt_note__c = grn.Id
        );
        update new List<Invoice_Line_Item__c>{updateInvoiceLine11, updateInvoiceLine12};
        
        // Create inventory records for the products
        /*Inventory__c inv1 = new Inventory__c(Product__c = product1.Id, Quantity_in_hand__c = 100, Distributor_Name__c = acc.Id);
        insert inv1;
        
        Inventory__c inv2 = new Inventory__c(Product__c = product2.Id, Quantity_in_hand__c = 200, Distributor_Name__c = acc.Id);
        insert inv2;*/
        
        Test.startTest();
        UpdateQuantityInHand.updatePrimaryInvoiceQuantity(new List<Invoice_Line_Item__c>{updateInvoiceLine12}, oldOrderMap);
        Test.stopTest();
    }
}