force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>This for the attendance functionality.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>IF(
    AND(NOT(ISBLANK(Leave_Date__c)), NOT(ISBLANK(Date_of_attendance__c))), 
    /* Both are not null, check if they are the same */
    IF(
        Leave_Date__c = Date_of_attendance__c, 
        Leave_Date__c, /* Both are the same, take the value */
        NULL /* Return null if both are different */
    ),
    /* If one of them is null, take the non-null value */
    IF(
        NOT(ISBLANK(Leave_Date__c)), 
        Leave_Date__c, 
        Date_of_attendance__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/First_Activity_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Activity_Time__c</fullName>
    <label>First Activity Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Checked_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Checked_In_Time__c</fullName>
    <label>Checked In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitTaskHandler.cls
public class VisitTaskHandler {
    
    public static void populateFirstActivity(Set<Id> visitTaskSet){
        if(visitTaskSet.isEmpty()){
            return;
        }else{
            Set<Id> userIds = new Set<Id>();
            Map<Id, Time> userCheckInMap = new Map<Id, Time>();
            for(Visit_Task__c vt : [SELECT Id , Checked_In_Time__c , Visitor_Name__c FROM Visit_Task__c WHERE Id IN: visitTaskSet]){
                if(vt.Checked_In_Time__c != null){
                    userIds.add(vt.Visitor_Name__c);
                    Time currentCheckInTime = vt.Checked_In_Time__c.time();
                    if (userCheckInMap.containsKey(vt.Visitor_Name__c)) {       
                        Time existingTime = userCheckInMap.get(vt.Visitor_Name__c);
                        if (currentCheckInTime < existingTime) {
                            userCheckInMap.put(vt.Visitor_Name__c, currentCheckInTime);
                        }
                    } else {
                        userCheckInMap.put(vt.Visitor_Name__c, currentCheckInTime);
                    }
                }               
            }
            
            if(userIds.size() > 0){
                Date today = Date.today();
                List<Attendance__c> attendanceList = [
                    SELECT Id, User__c, First_Activity_Time__c FROM Attendance__c
                    WHERE User__c IN :userIds AND Date__c = :today AND First_Activity_Time__c = NULL
                ];
                
                List<Attendance__c> updateList = new List<Attendance__c>();

                for (Attendance__c att : attendanceList) {
                    if (userCheckInMap.containsKey(att.User__c)) {
                        att.First_Activity_Time__c = userCheckInMap.get(att.User__c);
                        updateList.add(att);
                    }
                }
        
                if (!updateList.isEmpty()) {
                    update updateList;
                }
            }
        }
    }
}