force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>This for the attendance functionality.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>IF(
    AND(NOT(ISBLANK(Leave_Date__c)), NOT(ISBLANK(Date_of_attendance__c))), 
    /* Both are not null, check if they are the same */
    IF(
        Leave_Date__c = Date_of_attendance__c, 
        Leave_Date__c, /* Both are the same, take the value */
        NULL /* Return null if both are different */
    ),
    /* If one of them is null, take the non-null value */
    IF(
        NOT(ISBLANK(Leave_Date__c)), 
        Leave_Date__c, 
        Date_of_attendance__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Present Half Day</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Present Half Day / Absent</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Beat_Plan__c/Monthly_Beat_Plan__c.object-meta.xml
<CustomObject>
    <description>Used to plan and manage a salesman’s beat visits for a specific month</description>
    <label>Monthly Beat Plan</label>
    <nameField>
        <label>Monthly Beat Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Beat Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Beat_Name__c.field-meta.xml
<CustomField>
    <fullName>Beat_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Name</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Monthly Beat Plans</relationshipLabel>
    <relationshipName>Monthly_Beat_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Beat_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RetailerCodeSetting__c/RetailerCodeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RetailerCodeSetting</label>
</CustomObject>

force-app/main/default/objects/RetailerCodeSetting__c/fields/Latest_Code__c.field-meta.xml
<CustomField>
    <fullName>Latest_Code__c</fullName>
    <label>Latest_Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScheduleBeatPlanTest.cls
@isTest
public class ScheduleBeatPlanTest {

    @testSetup
    static void setupData() {
        RetailerCodeSetting__c setting = new RetailerCodeSetting__c(Name = 'SF', Latest_Code__c = 100);
        insert setting;

        /* -------- Create User -------- */
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@test.com',
            Username = 'testuser' + System.currentTimeMillis() + '@test.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = p.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;

        /* -------- Create Beat -------- */
        Beat__c beat = new Beat__c(
            Name = 'Test Beat'
        );
        insert beat;

        /* -------- Create Attendance (Present) -------- */
        Attendance__c attendance = new Attendance__c(
            User__c = testUser.Id,
            Status__c = 'Present'
        );
        insert attendance;

        /* -------- Create Monthly Beat Plan -------- */
        Monthly_Beat_Plan__c mbp = new Monthly_Beat_Plan__c(
            User__c = testUser.Id,
            Beat_Name__c = beat.Id,
            Date__c = Date.today(),
            IsActive__c = true
        );
        insert mbp;

        /* -------- Create Retailer Account -------- */
        RecordType retailerRT = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Account'
            AND Name = 'Retailer'
            LIMIT 1
        ];

        Account retailer = new Account(
            Name = 'Test Retailer',
            RecordTypeId = retailerRT.Id,
            Beats_Name__c = beat.Id
        );
        insert retailer;
    }

    @isTest
    static void testCreateVisitTask() {

        /* -------- Fetch Attendance -------- */
        Attendance__c attendance = [
            SELECT Id FROM Attendance__c LIMIT 1
        ];

        Set<Id> attendanceIds = new Set<Id>{ attendance.Id };

        Test.startTest();
        ScheduleBeatPlan.createVisitTask(attendanceIds);
        Test.stopTest();

        /* -------- Verify Visit Created -------- */
        List<Visit__c> visits = [
            SELECT Id, OwnerId, Beat__c
            FROM Visit__c
        ];
        System.assertEquals(1, visits.size(), 'Visit should be created');

        /* -------- Verify Visit Task Created -------- */
        List<Visit_Task__c> tasks = [
            SELECT Id, Visit__c, Retailer__c
            FROM Visit_Task__c
        ];
        System.assertEquals(1, tasks.size(), 'Visit Task should be created');
    }
    
    @isTest
    static void testCreateVisitTaskOnAttendanceChange() {
        User testUser = [SELECT Id FROM User WHERE isActive = true AND Profile.Name = 'SFA Profile' LIMIT 1];

        /* -------- Fetch Attendance -------- */
        Attendance__c attendance = new Attendance__c(
            User__c = testUser.Id,
            Status__c = 'Leave'
        );
        insert attendance;
        
        Attendance__c attendanceUpdate = new Attendance__c(
            Id = attendance.Id,
            User__c = testUser.Id,
            Status__c = 'Leave'
        );
        Update attendanceUpdate;

        Set<Id> attendanceIds = new Set<Id>{ attendanceUpdate.Id };

        Test.startTest();
        ScheduleBeatPlan.createVisitTask(attendanceIds);
        Test.stopTest();
    }

    @isTest
    static void testDuplicatePrevention() {

        Attendance__c attendance = [
            SELECT Id FROM Attendance__c LIMIT 1
        ];

        Set<Id> attendanceIds = new Set<Id>{ attendance.Id };

        Test.startTest();
        // First execution
        ScheduleBeatPlan.createVisitTask(attendanceIds);

        // Second execution (should not create duplicates)
        ScheduleBeatPlan.createVisitTask(attendanceIds);
        Test.stopTest();

        List<Visit__c> visits = [
            SELECT Id FROM Visit__c
        ];

        System.assertEquals(1, visits.size(),
            'Duplicate Visit should not be created');
    }
}