force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>This for the attendance functionality.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>IF(
    AND(NOT(ISBLANK(Leave_Date__c)), NOT(ISBLANK(Date_of_attendance__c))), 
    /* Both are not null, check if they are the same */
    IF(
        Leave_Date__c = Date_of_attendance__c, 
        Leave_Date__c, /* Both are the same, take the value */
        NULL /* Return null if both are different */
    ),
    /* If one of them is null, take the non-null value */
    IF(
        NOT(ISBLANK(Leave_Date__c)), 
        Leave_Date__c, 
        Date_of_attendance__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Leave_Period__c.field-meta.xml
<CustomField>
    <fullName>Leave_Period__c</fullName>
    <label>Leave Period</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Full Day</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Present Half Day</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Present Half Day / Absent</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Work__c.field-meta.xml
<CustomField>
    <fullName>Work__c</fullName>
    <label>Work</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Beat</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Official Meeting</fullName>
            </value>
            <value>
                <fullName>Outstation Visit</fullName>
            </value>
            <value>
                <fullName>Office Visit</fullName>
            </value>
            <value>
                <fullName>Distributor Visit</fullName>
            </value>
            <value>
                <fullName>Marketing Visit</fullName>
            </value>
            <value>
                <fullName>Working As PJP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_planned_date__c.field-meta.xml
<CustomField>
    <fullName>Visit_planned_date__c</fullName>
    <label>Visit planned date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Retailer_Address_New__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Address_New__c</fullName>
    <formula>IF(NOT(ISBLANK( Retailer__r.BillingStreet)), Retailer__r.BillingStreet, &apos;&apos;) &amp;
IF(NOT(ISBLANK(Retailer__r.BillingCity)),
IF(NOT(ISBLANK(Retailer__r.BillingStreet)), &apos;, &apos; &amp; Retailer__r.BillingCity, Retailer__r.BillingCity), &apos;&apos;) &amp;
IF(NOT(ISBLANK(Retailer__r.BillingState)),
IF(OR(NOT(ISBLANK(Retailer__r.BillingCity)), NOT(ISBLANK(Retailer__r.BillingStreet))), &apos;, &apos; &amp; Retailer__r.BillingState, Retailer__r.BillingState), &apos;&apos;) &amp;
IF(NOT(ISBLANK(Retailer__r.BillingPostalCode)),
IF(OR(NOT(ISBLANK(Retailer__r.BillingCity)), NOT(ISBLANK(Retailer__r.BillingState))), &apos; &apos; &amp; Retailer__r.BillingPostalCode, Retailer__r.BillingPostalCode), &apos;&apos;) &amp;
IF(NOT(ISBLANK(Retailer__r.BillingCountry)),
IF(OR(NOT(ISBLANK(Retailer__r.BillingCity)), NOT(ISBLANK(Retailer__r.BillingState)), NOT(ISBLANK(Retailer__r.BillingPostalCode))), &apos;, &apos; &amp; Retailer__r.BillingCountry, Retailer__r.BillingCountry), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retailer Address New</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserHierarchyController.cls
public without sharing class UserHierarchyController {

   @AuraEnabled(cacheable=true)
public static List<Attendance__c> getAllAttendanceRecords(List<Id> userIds, Date forDate) {
    System.debug('START: getAllAttendanceRecords');
    System.debug('Input userIds: ' + userIds);
    System.debug('Input forDate: ' + forDate);
    
    if (userIds == null || userIds.isEmpty() || forDate == null) {
        System.debug('Empty parameters. Returning empty list.');
        return new List<Attendance__c>();
    }
    
    List<Attendance__c> result = [
        SELECT Id, User__c, User__r.FirstName, User__r.LastName, 
               Status__c, Work__c, Date__c, Leave_Period__c
        FROM Attendance__c
        WHERE User__c IN :userIds 
        AND Date__c = :forDate
        AND Status__c IN ('Absent', 'Present', 'Leave', 'Present Half Day')
        ORDER BY User__r.LastName, User__r.FirstName
    ];
    
    System.debug('All Attendance records found: ' + result.size());
    System.debug('Attendance records: ' + JSON.serialize(result));
    
    return result;
}
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getAttendanceSummary(List<Id> userIds, Date forDate) {
        System.debug('START: getAttendanceSummary');
        System.debug('Input userIds: ' + userIds);
        System.debug('Input forDate: ' + forDate);
        
        Map<String, Integer> result = new Map<String, Integer>();
        result.put('Absent', 0);
        result.put('Leave', 0);
        result.put('Present', 0);
        result.put('Official Work', 0);
        result.put('Retailing', 0);
        
        if (userIds == null || userIds.isEmpty()) {
            System.debug('userIds is NULL or EMPTY. Returning zeroed map.');
            return result;
        }
        
        List<Attendance__c> atts = [
            SELECT Id, User__c, Status__c, Work__c, Date__c
            FROM Attendance__c
            WHERE User__c IN :userIds AND Date__c = :forDate
        ];
        
        System.debug('Attendance records found: ' + atts.size());
        
        Set<Id> countedRetailingUsers = new Set<Id>();
        
        for (Attendance__c a : atts) {
            String status = a.Status__c == null ? '' : a.Status__c.trim();
            String work   = a.Work__c == null ? '' : a.Work__c.trim();
            
            if (status == 'Leave') {
                result.put('Leave', result.get('Leave') + 1);
                continue; // once absent, skip other checks
            }
             if (status == 'Absent') {
                result.put('Absent', result.get('Absent') + 1);
                continue; // once absent, skip other checks
            }
            
            if (status == 'Present') {
                result.put('Present', result.get('Present') + 1);
                
                if (work == 'Official Meeting') {
                    result.put('Official Work', result.get('Official Work') + 1);
                }
                
                if (work == 'Audit' || work == 'Beat') {
                    if (a.User__c != null && !countedRetailingUsers.contains(a.User__c)) {
                        countedRetailingUsers.add(a.User__c);
                        result.put('Retailing', result.get('Retailing') + 1);
                    }
                }
            }
        }
        
        System.debug('FINAL RESULT Attendance Summary (counts only): ' + result);
        return result;
    }
    
    @AuraEnabled//(cacheable=true)
    public static List<Attendance__c> getLeaveUsersfirst(List<Id> userIds) {
        System.debug('START: getLeaveUsers');
        System.debug('Input userIds: ' + userIds);
        
        List<Attendance__c> result = [SELECT Id, User__c, User__r.FirstName, User__r.LastName, Leave_Period__c, Status__c, Date__c FROM Attendance__c 
                                      WHERE User__c IN :userIds AND (Status__c = 'Leave' OR  Status__c = 'Present Half Day') AND Date__c = :Date.today()];
        
        System.debug('Leave Users found: ' + result.size());
        System.debug('Leave User records: ' + JSON.serialize(result));
        
        return result;
    }
    
    @AuraEnabled
    public static List<Map<String, String>> getLeaveUsers(List<Id> userIds) {
        system.debug('userIds = ' + userIds);
        List<Map<String,String>> resultMap = new List<Map<String,String>>();
        
        for (Attendance__c att : [
            SELECT Id, User__c, User__r.FirstName, User__r.LastName, Leave_Period__c, Status__c, Date__c 
            FROM Attendance__c 
            WHERE User__c IN :userIds AND (Status__c = 'Leave' OR  Status__c = 'Present Half Day' ) AND Date__c = :Date.today()
        ]) {
            Map<String,String> m = new Map<String,String>();
            m.put('Id', att.Id);
            m.put('UserId', att.User__c);
            m.put('UserName', att.User__r.FirstName + ' ' + att.User__r.LastName);
            m.put('LeavePeriod', String.valueOf(att.Leave_Period__c));
            m.put('Status', att.Status__c);
            m.put('Date', String.valueOf(att.Date__c));
            resultMap.add(m);
        }
        
        return resultMap;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Visit__c> getRetailingDetails(List<Id> userIds) {
        System.debug('⚡ START: getRetailingDetails');
        System.debug('➡ Input userIds: ' + userIds);
        
        List<Visit__c> visits = [
            SELECT Id, Visitor_Name__c, Visitor_Name__r.FirstName, Visitor_Name__r.LastName, Beat__c, Beat__r.Name, 
            (SELECT Id, Retailer_Address_New__c 
             FROM Visit_Tasks__r 
             WHERE Status__c = 'In-Progress'
             LIMIT 1)
            FROM Visit__c
            WHERE Visitor_Name__c IN :userIds AND Visit_planned_date__c = :Date.today()
        ];
        
        System.debug('✅ Retailing records found: ' + visits.size());
        System.debug('🟢 Retailing Details: ' + JSON.serialize(visits));
        
        return visits;
    }
}