force-app/main/default/objects/Archival_Job_Log__c/Archival_Job_Log__c.object-meta.xml
<CustomObject>
    <label>Archival Job Log</label>
    <nameField>
        <displayFormat>AJL-{0000}</displayFormat>
        <label>Archival Job Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archival_Job_Log__c/fields/Archive_Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Archive_Batch_Id__c</fullName>
    <label>Archive Batch Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Job_Log__c/fields/Total_Archived__c.field-meta.xml
<CustomField>
    <fullName>Total_Archived__c</fullName>
    <label>Total Archived</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Azure_Archive_Config__mdt/Azure_Archive_Config__mdt.object-meta.xml
<CustomObject>
    <description>One row per in-scope object – retention days, closed-state values, batch enabled flag, dashboard cap</description>
    <label>Azure Archive Config</label>
    <pluralLabel>Azure  Archive Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Azure_Archive_Config__mdt/fields/Closed_State_Values__c.field-meta.xml
<CustomField>
    <fullName>Closed_State_Values__c</fullName>
    <description>SOQL where clause fragment for closed-parent test</description>
    <label>Closed State Values</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Azure_Archive_Config__mdt/fields/Retention_Days__c.field-meta.xml
<CustomField>
    <fullName>Retention_Days__c</fullName>
    <defaultValue>90</defaultValue>
    <description>Days since CreatedDate before eligible; default 90</description>
    <label>Retention Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Count_of_Cancelled_Task__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Cancelled_Task__c</fullName>
    <label>Count of Cancelled Task</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Status__c</field>
        <operation>equals</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Count_of_Completed_No_Order_Task__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Completed_No_Order_Task__c</fullName>
    <label>Count of Completed - No Order Task</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Status__c</field>
        <operation>equals</operation>
        <value>Completed - No Order</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Count_of_Completed_Order_Task__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Completed_Order_Task__c</fullName>
    <label>Count of Completed - Order Task</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Status__c</field>
        <operation>equals</operation>
        <value>Completed - Order</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Count_of_In_progress_Task__c.field-meta.xml
<CustomField>
    <fullName>Count_of_In_progress_Task__c</fullName>
    <label>Count of In-progress Task</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Status__c</field>
        <operation>equals</operation>
        <value>In-Progress</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Count_of_Not_Started_Task__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Not_Started_Task__c</fullName>
    <label>Count of Not Started Task</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Status__c</field>
        <operation>equals</operation>
        <value>Not Started</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Count_Completed_No_Order_Task__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Count_Completed_No_Order_Task__c</fullName>
    <label>Snapshot Count Completed No Order Task</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Count_of_Cancelled_Task__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Count_of_Cancelled_Task__c</fullName>
    <label>Snapshot Count of Cancelled Task</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Count_of_Completed_Order_Task__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Count_of_Completed_Order_Task__c</fullName>
    <label>Snapshot Count of Completed Order Task</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Count_of_In_Progress_Task__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Count_of_In_Progress_Task__c</fullName>
    <label>Snapshot Count of In Progress Task</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Count_of_Not_Started_Task__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Count_of_Not_Started_Task__c</fullName>
    <label>Snapshot Count of Not Started Task</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Total_Ad_Hoc_Visit__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Total_Ad_Hoc_Visit__c</fullName>
    <label>Snapshot Total Ad Hoc Visit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Total_Check_In_Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Total_Check_In_Check_Out_Time__c</fullName>
    <label>Snapshot Total Check In Check Out Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Total_Planned_Visit__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Total_Planned_Visit__c</fullName>
    <label>Snapshot Total Planned Visit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Snapshot_Total_Tasks_for_Visit__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Total_Tasks_for_Visit__c</fullName>
    <label>Snapshot Total Tasks for Visit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Total_Ad_Hoc_Visits__c.field-meta.xml
<CustomField>
    <fullName>Total_Ad_Hoc_Visits__c</fullName>
    <label>Total Ad Hoc Visits</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Visit_Type__c</field>
        <operation>equals</operation>
        <value>Ad-Hoc</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Total_Check_In_and_Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_In_and_Check_Out_Time__c</fullName>
    <label>Total Check In and Check Out Time</label>
    <summarizedField>Visit_Task__c.Total_Check_In_and_Check_Out_Time__c</summarizedField>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Total_planned_Visit__c.field-meta.xml
<CustomField>
    <fullName>Total_planned_Visit__c</fullName>
    <label>Total planned Visit</label>
    <summaryFilterItems>
        <field>Visit_Task__c.Visit_Type__c</field>
        <operation>equals</operation>
        <value>Planned</value>
    </summaryFilterItems>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Total_Tasks_for_Visit__c.field-meta.xml
<CustomField>
    <fullName>Total_Tasks_for_Visit__c</fullName>
    <label>Total Tasks for Visit</label>
    <summaryForeignKey>Visit_Task__c.Visit__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Total_Check_In_and_Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_In_and_Check_Out_Time__c</fullName>
    <formula>( Checked_Out_Time__c - Checked_In_Time__c ) * 24 * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Check In and Check Out Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ArchiveVisitTasksBatch.cls
global class ArchiveVisitTasksBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful, Schedulable {

    private Integer totalProcessed = 0;
    private Integer totalArchived = 0;
    private Integer totalFailed = 0;
    private List<String> errorMessages = new List<String>();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        Azure_Archive_Config__mdt confg = Azure_Archive_Config__mdt.getInstance('Visit_Task');

        Date cutoffDate = Date.today().addDays(-(Integer)confg.Retention_Days__c);

        Map<String, Schema.SObjectField> fieldMap = Visit_Task__c.SObjectType.getDescribe().fields.getMap();
        Set<String> excludedFields = new Set<String>{
            'LastActivityDate', 'LastReferencedDate', 'LastViewedDate', 'RecordVisibilityId', 'UserRecordAccessId'
        };

        List<String> fieldNames = new List<String>();

        for (String fieldName : fieldMap.keySet()) {
            if(!excludedFields.contains(fieldName)){
                    fieldNames.add(fieldName);
            }
        }

        String query = 'SELECT ' + String.join(fieldNames, ',') +
                        ' FROM Visit_Task__c ';
        if(!String.isBlank(confg.Closed_State_Values__c)){
            query += (String)confg.Closed_State_Values__c;
        }

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc,List<Visit_Task__c> scope) {
        DateTime archivedTimestamp = DateTime.now();
        Set<Id> visitIdSet = new Set<Id>();
        List<Visit_Task__c> visitTasksToUpdate = new List<Visit_Task__c>();
        List<Visit__c> visitsToUpdate = new List<Visit__c>();
        totalProcessed += scope.size();

        ArchiveConnectorService.SendResult r = ArchiveConnectorService.send('Visit_Task__c', scope, bc.getJobId());

        if (r.success) {
            System.debug('success:-' + r.success);
            try {
                System.debug('scope:-' + scope);
                System.debug('archivedIds:-' + r.archivedIds);
                for (Visit_Task__c item : scope) {
                    if(r.archivedIds.contains(item.id)){
                        visitIdSet.add(item.Visit__c);
                        visitTasksToUpdate.add(new Visit_Task__c(
                            Id = item.Id,
                            Archived__c = true,
                            Archived_Date__c = archivedTimestamp
                        ));
                    }
                }
                totalArchived += visitTasksToUpdate.size();
                TriggerBypass.bypassed.add('Visit_Task__c');   // bypass ON (visit task triggers)
                TriggerBypass.bypassed.add('Visit__c');       // bypass ON (visit triggers)
                Database.update(visitTasksToUpdate, false);
                
                for(Visit__c v : [SELECT Id, Count_of_Completed_No_Order_Task__c, Count_of_Cancelled_Task__c, Count_of_Completed_Order_Task__c,
                                   Count_of_In_Progress_Task__c, Count_of_Not_Started_Task__c, Total_Ad_Hoc_Visits__c,
                                   Total_Check_In_and_Check_Out_Time__c, Total_Planned_Visit__c, Total_Tasks_for_Visit__c
                                   FROM Visit__c WHERE Id IN :visitIdSet]){
                    v.Snapshot_Count_Completed_No_Order_Task__c   = v.Count_of_Completed_No_Order_Task__c;
                    v.Snapshot_Count_of_Cancelled_Task__c         = v.Count_of_Cancelled_Task__c;
                    v.Snapshot_Count_of_Completed_Order_Task__c   = v.Count_of_Completed_Order_Task__c;
                    v.Snapshot_Count_of_In_Progress_Task__c       = v.Count_of_In_Progress_Task__c;
                    v.Snapshot_Count_of_Not_Started_Task__c       = v.Count_of_Not_Started_Task__c;
                    v.Snapshot_Total_Ad_Hoc_Visit__c              = v.Total_Ad_Hoc_Visits__c;
                    v.Snapshot_Total_Check_In_Check_Out_Time__c   = v.Total_Check_In_and_Check_Out_Time__c;
                    v.Snapshot_Total_Planned_Visit__c             = v.Total_Planned_Visit__c;
                    v.Snapshot_Total_Tasks_for_Visit__c           = v.Total_Tasks_for_Visit__c;
                    visitsToUpdate.add(v);
                }

                if(!visitsToUpdate.isEmpty()){
                    update visitsToUpdate;
                }

            } catch (DmlException e) {
                for (Integer i = 0; i < e.getNumDml(); i++) {
                    System.debug('DML Error ' + i + ': ' + e.getDmlMessage(i));
                    System.debug('Status Code: ' + e.getDmlStatusCode(i));
                    System.debug('Fields: ' + e.getDmlFieldNames(i));
                }
            }
        } else {
            System.debug('Error while Archiving: ' + r.errorMessage);
            totalFailed += scope.size();
            errorMessages.add(r.errorCode + '-' + r.errorMessage);
        }
    }

    global void finish(Database.BatchableContext bc) {

        System.debug('Archival job completed.');
        Archival_Job_Log__c ajl = new Archival_Job_Log__c(
            Archive_Batch_Id__c   = bc.getJobId(),
            Archived_Object__c    = 'Visit_Task__c',
            Error_Message__c      = errorMessages.isEmpty() ? null : String.join(errorMessages, '; '),
            Total_Archived__c     = totalArchived,
            Total_Failed__c       = totalFailed,
            Total_Processed__c    = totalProcessed
        );
        insert ajl;
    }

     global void execute(SchedulableContext sc) {
        Database.executeBatch(new ArchiveVisitTasksBatch(), 200);
    }
}