force-app/main/default/objects/Delivery_Plan__c/Delivery_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the delivery plan from DMS portal</description>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Delivery Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Plan_Items__c/Delivery_Plan_Items__c.object-meta.xml
<CustomObject>
    <label>Delivery Plan Item</label>
    <nameField>
        <displayFormat>Items-{0000}</displayFormat>
        <label>Delivery Plan Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Plan_Items__c/fields/Delivery_Plan__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plan__c</fullName>
    <label>Delivery Plan</label>
    <referenceTo>Delivery_Plan__c</referenceTo>
    <relationshipLabel>Delivery Plan Item</relationshipLabel>
    <relationshipName>Delivery_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Plan_Items__c/fields/Invoices__c.field-meta.xml
<CustomField>
    <fullName>Invoices__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Delivery Plan Item(Invoices)</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <description>To capture the CGST amount on an Invoice Record</description>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount__c</fullName>
    <description>To capture the IGST amount on an Invoice Record</description>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Retailer_Account__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link Invoice record with a Retailer Account</description>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Retailer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <description>To capture the SGST amount on an Invoice Record</description>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Under_SS__c.field-meta.xml
<CustomField>
    <fullName>Under_SS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Under SS</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Under SS)</relationshipLabel>
    <relationshipName>UnderSS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Invoice-Item-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount__c</fullName>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>To link Invoice Line Items to an Invoice Record</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>To capture ordered Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture ordered Product</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>To capture the ordered Product Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit Of Measure</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <label>Picklist</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Picklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EWayBillExcelController.cls
/**
* Class Name  : EWayBillExcelController
* Test Class  : EWayBillExcelControllerTest
* Author      : Mirza
* CreatedDate : 30-04-25
* Description : Controller class of vf page (EWayBillExcel) to fetch invoice and invoice line item details to generate E-way bill for the delivery plan record
* */
public class EWayBillExcelController {
    
    public Id deliveryPlanId { get; set; } 
    public List<Delivery_Plan_Items__c> deliveryPlanItemList {get; set;}
    public List<Invoice__c> invoiceList {get; set;}
    public Date currentDate { get; set; }
    
    public EWayBillExcelController(){
        deliveryPlanId = ApexPages.currentPage().getParameters().get('Id');  //To store delivery plan record Id
        Set<String> invoiceId = new Set<String>();                           //Set to store invoice Id tagged to the delivery plan item
        String deliveryPlanName;
        
        if(deliveryPlanId != Null){
            deliveryPlanItemList = [SELECT Id , Name , Invoices__c , Delivery_Plan__c , Delivery_Plan__r.Name FROM Delivery_Plan_Items__c WHERE Delivery_Plan__c =: deliveryPlanId];
            for(Delivery_Plan_Items__c deliveryPlanItemRecord : deliveryPlanItemList){
                invoiceId.add(deliveryPlanItemRecord.Invoices__c);
                deliveryPlanName = deliveryPlanItemRecord.Delivery_Plan__r.Name;
            }
        }
        
        if(invoiceId.size()>0){
            invoiceList = fetchInvoiceData(invoiceId);
            currentDate = Date.today();
            String filename = deliveryPlanName + '_EWayBill.xls';
            ApexPages.currentPage().getHeaders().put('Content-Disposition', 'attachment; filename="' + filename + '"');
        }
    }
    
    //Method to fetch invoice and invoice line item details
    public List<Invoice__c> fetchInvoiceData(Set<String> invoiceIdSet) {
        return [
            SELECT Name, Invoice_Date__c, RecordType.DeveloperName,
                   Distributor_Account__r.Name,
                   Distributor_Account__r.GSTIN__c,
                   Distributor_Account__r.BillingStreet,
                   Distributor_Account__r.BillingCity,
                   Distributor_Account__r.BillingPostalCode,
                   Distributor_Account__r.BillingState,
                   Distributor_Account__r.ShippingState,
                   Retailer_Account__r.Name,
                   Retailer_Account__r.GSTIN__c,
                   Retailer_Account__r.BillingStreet,
                   Retailer_Account__r.BillingCity,
                   Retailer_Account__r.BillingPostalCode,
                   Retailer_Account__r.BillingState,
                   Retailer_Account__r.ShippingState,
                   Under_SS__r.Name,
                   Under_SS__r.GSTIN__c,
                   Under_SS__r.BillingStreet,
                   Under_SS__r.BillingCity,
                   Under_SS__r.BillingPostalCode,
                   Under_SS__r.BillingState,
                   Under_SS__r.ShippingState,
                   (SELECT Product__r.Name, Product__r.HSN__c, Product__r.Unit_of_Measure__c, Quantity__c,
                           Price__c, CGST_Amount__c, SGST_Amount__c,
                           IGST_Amount__c, Total_Amount__c
                    FROM Invoice_Line_Items__r)
            FROM Invoice__c
            WHERE Id IN: invoiceIdSet
            ORDER BY CreatedDate DESC
        ];
    }
}