force-app/main/default/objects/Delivery_Plan__c/Delivery_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the delivery plan from DMS portal</description>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Delivery Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Plan__c/fields/Driver_Name__c.field-meta.xml
<CustomField>
    <fullName>Driver_Name__c</fullName>
    <label>Driver Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Plan__c/fields/Driver_Number__c.field-meta.xml
<CustomField>
    <fullName>Driver_Number__c</fullName>
    <label>Driver Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <label>Picklist</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Picklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Crate__c.field-meta.xml
<CustomField>
    <fullName>Crate__c</fullName>
    <formula>IF ( AND(
NOT(ISBLANK(Quantity__c)) ,
NOT(ISBLANK(Product__r.Crate_Conversion__c))
) ,
TEXT(FLOOR(Quantity__c/Product__r.Crate_Conversion__c)) &amp; &quot; Crate &quot; &amp; TEXT(MOD(Quantity__c,Product__r.Crate_Conversion__c)) &amp; &quot; EA &quot; ,
&apos; &apos;)</formula>
    <label>Crate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Delivery_Plan__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plan__c</fullName>
    <label>Delivery Plan</label>
    <referenceTo>Delivery_Plan__c</referenceTo>
    <relationshipLabel>Picklist(Delivery Plan)</relationshipLabel>
    <relationshipName>DeliveryPlan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount__c</fullName>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PicklistPDFController.cls
public with sharing class PicklistPDFController {
    public Id deliveryPlanId { get; set; } 
    public List<Picklist__c> picklistRecords { get; private set; }
    public Contact loggedInContact { get; set; } // Renamed to loggedInContact for clarity
    public List<Delivery_Plan__c> deliveryPlans { get; set; }
    public String formattedDate { get; set; } 

    
    // Constructor
    public PicklistPDFController() {
        // Capture the Delivery Plan ID from the page URL
        deliveryPlanId = ApexPages.currentPage().getParameters().get('id');

        // Query the Picklist records only if a valid ID is provided
        if (deliveryPlanId != null) {
            picklistRecords = [
                SELECT Name,Product__r.Name, Quantity__c, Unit_Price__c, UOM__c, Gross_Amount__c , Crate__c
                FROM Picklist__c
                WHERE Delivery_Plan__c = :deliveryPlanId
            ];
		/*if(!picklistRecords.isEmpty()){
            	String filename = picklistRecords[0].Name ;
            	ApexPages.currentPage().getHeaders().put('Content-Disposition', 'attachment; filename="' + filename + '"');
        	} */
            // Fetch the related Delivery Plan
            deliveryPlans = [
                SELECT Driver_Name__c, Driver_Number__c, Vehicle_Number__c, Date__c
                FROM Delivery_Plan__c
                WHERE Id = :deliveryPlanId
            ];   
            if (!deliveryPlans.isEmpty()) {
            // Format the Date__c field in a readable format (e.g., 'MM/dd/yyyy')
            formattedDate = deliveryPlans[0].Date__c.format();
        	}
        } else {
            picklistRecords = new List<Picklist__c>(); 
        }

        // Get logged-in user's ContactId
        User usr = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        
        // Get the Contact record for the logged-in user
        if (usr.ContactId != null) {
        loggedInContact = [SELECT Id, AccountId, Account.Name,Account.Owners_Number__c, Account.Phone, Account.ShippingStreet, Account.ShippingCity, 
                                  Account.ShippingState, Account.ShippingPostalCode, 
                                  Account.ShippingCountry
                           FROM Contact
                           WHERE Id = :usr.ContactId
                           LIMIT 1];
        }
    }
   

    public void setContentDispositionpdf() {
        if(picklistRecords.isEmpty()) return;

       String filename = picklistRecords[0].Name + '.PDF';
            	ApexPages.currentPage().getHeaders().put('Content-Disposition', 'attachment; filename="' + filename + '"');
       
    }
      public void setContentDispositionexcel() {
        if(picklistRecords.isEmpty()) return;

        String filename = picklistRecords[0].Name + '.xls';
       
            ApexPages.currentPage().getHeaders().put('Content-Type', 'application/vnd.ms-excel');
            ApexPages.currentPage().getHeaders().put('Content-Disposition', 'attachment; filename="' + filename + '"');
        }
    
}