force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <description>To store the CGST Value applied while calculating the invoice amount</description>
    <label>CGST %</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Discount_1__c.field-meta.xml
<CustomField>
    <fullName>Discount_1__c</fullName>
    <label>TOD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Discount_2__c.field-meta.xml
<CustomField>
    <fullName>Discount_2__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <description>To store the IGST Value applied while calculating the invoice amount</description>
    <label>IGST %</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link Invoice records for an Order</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Retailer_Account__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link Invoice record with a Retailer Account</description>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Retailer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <description>To store the SGST Value applied while calculating the invoice amount</description>
    <label>SGST %</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Invoice-Item-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount_1__c.field-meta.xml
<CustomField>
    <fullName>Discount_1__c</fullName>
    <label>TOD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount_2__c.field-meta.xml
<CustomField>
    <fullName>Discount_2__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>To link Invoice Line Items to an Invoice Record</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture ordered Product</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <formula>Product__r.Product_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>To capture the ordered Product Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_tax_value__c/Order_tax_value__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Order tax value</label>
</CustomObject>

force-app/main/default/objects/Order_tax_value__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_tax_value__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <label>IGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_tax_value__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <label>SGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Entry__c/Price_Book_Entry__c.object-meta.xml
<CustomObject>
    <label>Price Book Entry</label>
    <nameField>
        <label>Price Book Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Book Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Entry__c/fields/PTR__c.field-meta.xml
<CustomField>
    <fullName>PTR__c</fullName>
    <label>PTR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/RetailerCodeSetting__c/RetailerCodeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RetailerCodeSetting</label>
</CustomObject>

force-app/main/default/objects/RetailerCodeSetting__c/fields/Latest_Code__c.field-meta.xml
<CustomField>
    <fullName>Latest_Code__c</fullName>
    <label>Latest_Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateInvoiceSchedulerTest.cls
@isTest
private class UpdateInvoiceSchedulerTest {

    @testSetup
    static void setupData() {
        // ---- Record Types ----
        Id retailerRT = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        Id productRT  = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Product').getRecordTypeId();
        Id invoiceRT  = Schema.SObjectType.Invoice__c.getRecordTypeInfosByName().get('Secondary Invoice').getRecordTypeId();
        
        RetailerCodeSetting__c setting = new RetailerCodeSetting__c(Name = 'SF', Latest_Code__c = 100);
        insert setting;
        
        // ---- Retailer Account ----
        Account retailer = new Account(
            Name = 'Test Retailer',
            RecordTypeId = retailerRT,
            Primary_State__c = 'Maharashtra'
        );
        insert retailer;

        // ---- Product ----
        Product__c prod = new Product__c(
            Name = 'Test Product',
            Product_Code__c = 'TP-001',
            RecordTypeId = productRT,
            IsActive__c = true
        );
        insert prod;

        // ---- Custom Price Book (State Specific) ----
        Price_Book__c priceBook = new Price_Book__c(
            Name = 'Maharashtra',
            IsActive__c = true
        );
        insert priceBook;

        // ---- Price Book Entry ----
        Price_Book_Entry__c pbe = new Price_Book_Entry__c(
            Product__c = prod.Id,
            Price_Book__c = priceBook.Id,
            PTR__c = 100.50,
            IsActive__c = true
        );
        insert pbe;

        // ---- Order ----
        Order__c ord = new Order__c(
            Account__c = retailer.Id
            //CreatedDate = System.now().addDays(-3) // Before cutoff
        );
        insert ord;
        Datetime customCreatedDate = Datetime.newInstance(2025, 9, 22, 16, 59, 0);
        Test.setCreatedDate(ord.Id, customCreatedDate);

        // ---- Invoice ----
        Invoice__c inv = new Invoice__c(
            Name = 'Test Invoice',
            Order__c = ord.Id,
            Retailer_Account__c = retailer.Id,
            RecordTypeId = invoiceRT
           // CreatedDate = System.now() // After cutoff
        );
        insert inv;
        Test.setCreatedDate(inv.Id, System.now());
        // ---- Invoice Line Item ----
        Invoice_Line_Item__c line = new Invoice_Line_Item__c(
            Invoice__c = inv.Id,
            Product__c = prod.Id,
            Quantity__c = 5,
            Discount_1__c = 10,
            Discount_2__c = 5
        );
        insert line;

        // ---- Tax Setting ----
        Order_Tax_Value__c tax = new Order_Tax_Value__c(
            Name = 'General GST Settings',
            CGST__c = 9,
            SGST__c = 9,
            IGST__c = 18
        );
        insert tax;
    }

    @isTest
    static void testSchedulerExecution() {
        Test.startTest();

        // Run scheduler once
        String cron = '0 0 0 * * ?'; // midnight
        System.schedule('Test UpdateInvoiceScheduler', cron, new UpdateInvoiceScheduler());

        Test.stopTest();

      
    }
}