force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <description>To capture total amount including tax</description>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Custom Invoice Number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Retailer_Account__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link Invoice record with a Retailer Account</description>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Retailer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <description>To capture the Invoice Line Item&apos;s total quantity</description>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Under_SS__c.field-meta.xml
<CustomField>
    <fullName>Under_SS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Under SS</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Under SS)</relationshipLabel>
    <relationshipName>UnderSS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Invoice-Item-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>To link Invoice Line Items to an Invoice Record</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <formula>if( Invoice__r.Invoice_Number__c != NULL,
    Invoice__r.Invoice_Number__c,
    Invoice__r.Name 
  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>To capture ordered Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture ordered Product</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>To capture the ordered Product Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <label>Picklist</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Picklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Under_SS__c.field-meta.xml
<CustomField>
    <fullName>Under_SS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Under SS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExportInvoiceToExcelController.cls
public class ExportInvoiceToExcelController {
    
    public Id invoiceId { get; set; }
    public List<Invoice__c> invoices { get; set; }
    public List<Invoice_Line_Item__c> invoiceLineItems { get; set; }
    public String retailerName { get; set; }
    
    public ExportInvoiceToExcelController(){
        invoiceId = ApexPages.currentPage().getParameters().get('Id');
        System.debug('invoiceId=> ' + invoiceId);
        if(invoiceId != null){
            invoices = [SELECT Id, Invoice_Number__c , Invoice_Date__c , Retailer_Account__r.Name, Under_SS__r.Name , Invoice_Amount__c , Total_Quantity__c FROM Invoice__c WHERE Id =: invoiceId LIMIT 1];
            if(invoices[0].Retailer_Account__r.Name != null){
                retailerName = invoices[0].Retailer_Account__r.Name;
            }else{
                retailerName = invoices[0].Under_SS__r.Name;
            }
            invoiceLineItems = [SELECT Id,Name, Product__r.Name, Price__c , Quantity__c, Total_Amount__c FROM Invoice_Line_Item__c WHERE Invoice__c = :invoiceId];
        }
        // Dynamically set the filename based on the order's name
        String filename = invoices[0].Invoice_Number__c + '_InvoiceDetails.xls';
        ApexPages.currentPage().getHeaders().put('Content-Disposition', 'attachment; filename="' + filename + '"');
    }
}