force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SuperStockist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>All_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Discount_Amount_Order__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount_Order__c</fullName>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Value__c</fullName>
    <label>Total Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Order</fullName>
            </value>
            <value>
                <fullName>Counter Order</fullName>
            </value>
            <value>
                <fullName>Under Super Stockist</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>Bulk Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Value_Scheme_Applied__c.field-meta.xml
<CustomField>
    <fullName>Value_Scheme_Applied__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Value Scheme Applied</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Visit_Task__c.field-meta.xml
<CustomField>
    <fullName>Visit_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Task</label>
    <referenceTo>Visit_Task__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>Order-Item-{0000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Ordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Quantity__c</fullName>
    <label>Ordered Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom product</description>
    <label>Products</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Quantity_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quantity Scheme Applied</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Ordered_Quantity__c  *  Product_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Same Product – Free</fullName>
            </value>
            <value>
                <fullName>Other Product – Free</fullName>
            </value>
            <value>
                <fullName>Other Product – Discounted</fullName>
            </value>
            <value>
                <fullName>Same Product – Discounted</fullName>
            </value>
            <value>
                <fullName>Flat Discount</fullName>
            </value>
            <value>
                <fullName>Free Product</fullName>
            </value>
            <value>
                <fullName>Purchase Quantity Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Tasks (Account)</relationshipLabel>
    <relationshipName>Visit_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order NA</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Task_Planned_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Planned_Date__c</fullName>
    <label>Task Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VisitSummaryPdfRecord.cls
public with sharing class VisitSummaryPdfRecord {
    @AuraEnabled
    public static List<Visit_Task__c> getBeatsForOrderDate(Date orderDate){
        List<Visit_Task__c> visitTaskList = [SELECT Id , Name , Beat__r.Name FROM Visit_Task__c WHERE Task_Planned_Date__c =: orderDate AND Beat__c != NULL];
        
        return visitTaskList;
    }
    
    @AuraEnabled
    public static String getDistributorName(String beatId){
        String distributorName = [SELECT Id , Distributor_Name__r.Name FROM Beat__c WHERE Id =: beatId and Distributor_Name__c != NULL LIMIT 1].Distributor_Name__c;
        
        return distributorName;
    }
   
    
    @AuraEnabled
    public static List<Order__c> fetchVisitSummaryDetail(String distributorId , Date orderDate){
        if (String.isEmpty(distributorId)){
            throw new AuraHandledException('Distributor ID cannot be null or empty.');
        }
        List<Order__c> orders = [SELECT Id , Name , AccountId__r.Name , Account__r.Name ,  EffectiveDate__c , Value_Scheme_Applied__r.Name , Discount_Amount_Order__c , Total_Order_Value__c , (SELECT Name , Products__r.Name , Product_Price__c , Ordered_Quantity__c , Quantity_Scheme__r.Name , Total_Amount__c FROM Order_Line_Items__r) FROM Order__c WHERE AccountId__c =: distributorId AND EffectiveDate__c =: orderDate AND Record_Type_Name__c = 'Secondary Order' AND Type__c = 'Field Order' ORDER BY Account__r.Name];
        
        return orders;
    }
    
    @AuraEnabled
    public static String generatePdfAndContentUrl(String distributorId, String orderDate) {
        String vfPageUrl = '/apex/VisitSummaryPdfPage?distributorId=' + EncodingUtil.urlEncode(distributorId, 'UTF-8') + '&orderDate=' + EncodingUtil.urlEncode(orderDate, 'UTF-8');
 
        // Generate PDF Blob
        PageReference pdfPage = new PageReference(vfPageUrl);
        Blob pdfBlob;
        if(!Test.isRunningTest()){
            pdfBlob = pdfPage.getContent();
        }
        else{
            pdfBlob = Blob.valueOf('Test Blob Content');
        }
 
        // Create Salesforce File (ContentDocument)
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'VisitSummary_' + orderDate + '.pdf';
        contentVersion.PathOnClient = 'VisitSummary.pdf';
        contentVersion.VersionData = pdfBlob;
        contentVersion.IsMajorVersion = true;
        insert contentVersion;
 
        // Get the newly created ContentDocument ID
        //ContentDocument doc = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId = :contentVersion.Id LIMIT 1];
 
        // Return the ContentDocument ID (not the URL)
        return contentVersion.Id;
    }
}