force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SuperStockist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar</fullName>
            </value>
            <value>
                <fullName>Daman</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Ladakh</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Puducherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateRetailerBeatController.cls
/**
* Class Name  : UpdateRetailerBeatController
* Test Class  : UpdateRetailerBeatControllerTest
* author      : Mirza
* CreatedDate : 19-2-25
* Description : This is used to update the beat in retailer record
* */
public with sharing class UpdateRetailerBeatController {
    
    @AuraEnabled
    public static List<Beat__c> getAllBeats(String searchValue) {
        String userId = UserInfo.getUserId();
        User currentUser = [
            SELECT Id, UserRoleId 
            FROM User 
            WHERE Id = :userId
            LIMIT 1
        ];
        // Get all subordinate user Ids
        Set<Id> userIds = new Set<Id>{userId}; // Include the logged-in user
        // Fetch subordinate roles and their users
        List<UserRole> subRoles = [
            SELECT Id 
            FROM UserRole 
            WHERE ParentRoleId = :currentUser.UserRoleId
        ];
        if (!subRoles.isEmpty()) {
            List<User> subUsers = [
                SELECT Id 
                FROM User 
                WHERE UserRoleId IN :subRoles
            ];
            for (User u : subUsers) {
                userIds.add(u.Id);
            }
        }
        
        String query = 'SELECT Id, Name,Territory__c , Distributor_Name__r.Name FROM Beat__c WHERE Employee_Name__c IN :userIds';      
        if (!String.isEmpty(searchValue)) {
            searchValue = '%' + searchValue + '%';
            query += ' AND Name LIKE :searchValue';
        }
        List<Beat__c> beats = Database.query(query);
        
        return beats;
    }
    
    @AuraEnabled
    public static List<Account> getAllRetailer(String searchValue) {
        String userId = UserInfo.getUserId();
        // Fetch the logged-in user's role
        User currentUser = [
            SELECT Id, UserRoleId 
            FROM User 
            WHERE Id = :userId
            LIMIT 1
        ];
        // Get all subordinate user Ids
        Set<Id> userIds = new Set<Id>{userId}; // Include the logged-in user
        // Fetch subordinate roles and their users
        List<UserRole> subRoles = [
            SELECT Id 
            FROM UserRole 
            WHERE ParentRoleId = :currentUser.UserRoleId
        ];
        if (!subRoles.isEmpty()) {
            List<User> subUsers = [
                SELECT Id 
                FROM User 
                WHERE UserRoleId IN :subRoles
            ];
            for (User u : subUsers) {
                userIds.add(u.Id);
            }
        }
        
        Id accountRecordTypeId = [
            SELECT Id FROM RecordType 
            WHERE Name = 'Retailer' AND SObjectType = 'Account' 
            LIMIT 1
        ].Id;
        String query = 'SELECT Id, Name,Owners_Number__c , Distributor__r.Name FROM Account WHERE OwnerId IN :userIds AND RecordTypeId = :accountRecordTypeId';      
        if (!String.isEmpty(searchValue)) {
            searchValue = '%' + searchValue + '%';
            query += ' AND Name LIKE :searchValue';
        }
        List<Account> getRetailer = Database.query(query);
        
        return getRetailer;
    }
    
    @AuraEnabled
    public static String updateRetailerRecord(List<Id> beatId , List<Id> retailerId) {
        System.debug('beatId: '+beatId);
        System.debug('retailerId: '+retailerId);
        List<Account> updateAAccountList = new List<Account>();
        if (!String.isEmpty(beatId[0]) && retailerId.size()>0){
            Account acc;
            for(Account accRecord : [SELECT Id, Name,Beats_Name__c FROM Account WHERE Id IN: retailerId]){
                acc = new Account();
                acc.Id = accRecord.Id;
                acc.Beats_Name__c = beatId[0];
                updateAAccountList.add(acc);
            }
        }
        try {
            update updateAAccountList;
            return 'Success';
        } catch (DmlException e) {
            throw new AuraHandledException('Error creating Visit Tasks: ' + e.getMessage());
        }
    }
}