force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar</fullName>
            </value>
            <value>
                <fullName>Daman</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Ladakh</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Puducherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_planned_date__c.field-meta.xml
<CustomField>
    <fullName>Visit_planned_date__c</fullName>
    <label>Visit planned date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Tasks (Account)</relationshipLabel>
    <relationshipName>Visit_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Task_Planned_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Planned_Date__c</fullName>
    <label>Task Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitSchedulerController.cls
/**
* Class Name  : VisitSchedulerController
* Test Class  : VisitSchedulerControllerTest
* author      : Shyam
* CreatedDate : 15-01-25	
* Description : This is controller for creating Visit & Visit Task on future (Selected Date).
                
* */
public with sharing class VisitSchedulerController {
    
    @AuraEnabled(cacheable=true)
    public static List<Beat__c> getAllBeats(Map<String, String> filterParams) {
        Set<Id> userIds = GetSubOrinates.getSubOrinatesUserIds();
        String query = 'SELECT Id, Name,Territory__c, Employee_Name__c FROM Beat__c WHERE OwnerId In :userIds';
        /*String userId = UserInfo.getUserId();
        String query = 'SELECT Id, Name,Territory__c, Employee_Name__c FROM Beat__c WHERE Employee_Name__c = :userId';*/     
        
        List<Beat__c> beats = Database.query(query);
        return beats;
    }
    
    @AuraEnabled
    public static List<Account> getRetailersByBeat(Id beatId) {
        Set<Id> userIds = GetSubOrinates.getSubOrinatesUserIds();
        if (beatId == null) {
            throw new IllegalArgumentException('Beat Id must not be null.');
        }
        Id retailerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();

        List<Account> retailerAccounts = [
            SELECT Id, Name, Beats_Name__c, Phone, Owners_Number__c
            FROM Account
            WHERE RecordTypeId = :retailerRecordTypeId
            AND Beats_Name__c = :beatId
            AND OwnerId IN :userIds AND Is_Active__c = true
        ];

        return retailerAccounts;
    }
    
    @AuraEnabled
    public static void createVisits(List<Id> retailerIds, Date visitDate, Id beatId) {
        /*if (retailerIds == null || retailerIds.isEmpty()) {
            throw new AuraHandledException('No retailers selected.');
        }
        if (visitDate == null) {
            throw new AuraHandledException('Visit date is not provided.');
        }
        if (beatId == null) {
            throw new AuraHandledException('No Beat selected.');
        }*/
        
         // Check if a visit already exists for the selected date and beat for the logged-in user
    List<Visit__c> existingVisits = [
        SELECT Id
        FROM Visit__c
        WHERE Visit_planned_date__c = :visitDate
        AND Visitor_Name__c = :UserInfo.getUserId()
        //AND Beat__c = :beatId
    ];
    
    if (!existingVisits.isEmpty()) {
        throw new AuraHandledException('A visit already exists for the selected date and beat.');
    }
       
            Visit__c visit = new Visit__c(
                Visit_planned_date__c = visitDate,
                Visitor_Name__c = UserInfo.getUserId(),
                Beat__c = beatId,
                Status__c = 'Not Started',
                Visit_Type__c = 'Planned'

            );
            try {
                insert visit;
            } catch (DmlException e) {
                throw new AuraHandledException('Error creating new Visit: ' + e.getMessage());
            }
        

        // Create Visit_Task__c records for each selected retailer
        List<Visit_Task__c> tasksToInsert = new List<Visit_Task__c>();
        for (Id retailerId : retailerIds) {
            Visit_Task__c visitTask = new Visit_Task__c(
                Visit__c = visit.Id,
                Retailer__c = retailerId,
                Account__c = retailerId,
                Beat__c = beatId,
                Task_Planned_Date__c = visit.Visit_planned_date__c,
                Status__c = 'Not Started',
                Visit_Type__c = 'Planned',
                Visitor_Name__c = visit.Visitor_Name__c
            );
            tasksToInsert.add(visitTask);
        }

        // Insert Visit_Task__c records
        try {
            insert tasksToInsert;
        } catch (DmlException e) {
            throw new AuraHandledException('Error creating Visit Tasks: ' + e.getMessage());
        }
    }
    
    
    
    
    
    
}