force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>IN - {0000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventorys</relationshipLabel>
    <relationshipName>Inventorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_in_hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_in_hand__c</fullName>
    <label>Quantity in hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>All_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>Order-Item-{0000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Ordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Quantity__c</fullName>
    <label>Ordered Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product To be deleted</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom product</description>
    <label>Products</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/CounterOrderInventoryValidation.cls
public class CounterOrderInventoryValidation {
    
    public static void checkInventory(List<Order__c> orderList , Map<Id, Order__c> oldOrderMap){
        Set<Id> orderId = new Set<Id>();
        Set<Id> productId = new Set<Id>();
        Map<String, Inventory__c> inventoryMap = new Map<String, Inventory__c>();
        Map<Id, Order__c> orderMap = new Map<Id, Order__c>();
        String distributorName;
        for(Order__c ord:orderList){
            if(ord.Status__c == 'Delivered' && oldOrderMap.get(ord.Id).Status__c != 'Delivered'){
                orderId.add(ord.Id);
                orderMap.put(ord.Id, ord);
                distributorName = ord.AccountId__c;
            }
        }
        
        if (!orderId.isEmpty()){
            List<Order_Line_Item__c> orderLineItems = [
                SELECT Id, Order__c, Products__c, Products__r.Name ,Ordered_Quantity__c,Order__r.AccountId__c
                FROM Order_Line_Item__c
                WHERE Order__c IN: orderId AND Order__r.Record_Type_Name__c = 'Counter Order'
            ];
            
            for(Order_Line_Item__c lineItem : orderLineItems){
                if(lineItem.Products__c != null || lineItem.Order__r.AccountId__c != null){
                    productId.add(lineItem.Products__c);
                }
            }
            
            for (Inventory__c invt : [SELECT Id, Distributor_Name__c, Product__c, Quantity_in_hand__c FROM Inventory__c WHERE Distributor_Name__c =:distributorName AND Product__c IN: productId]){
                inventoryMap.put(invt.Product__c , invt);
            }
            
            for (Order_Line_Item__c lineItem : orderLineItems){
                Inventory__c matchingInventory = inventoryMap.get(lineItem.Products__c);
                Order__c targetOrder = orderMap.get(lineItem.Order__c);
                if(matchingInventory == null){
                    targetOrder.addError('No matching inventory found for Distributor ' 
                    + lineItem.Order__r.AccountId__c + ' and Product ' + lineItem.Products__c);
                }else if(matchingInventory.Quantity_in_hand__c < lineItem.Ordered_Quantity__c){
                    targetOrder.addError('Insufficient inventory for ' 
                    + lineItem.Products__r.Name + '. Available: ' + matchingInventory.Quantity_in_hand__c + 
                    ', Required: ' + lineItem.Ordered_Quantity__c);
                }
            }
        }
    }

}