force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>IN - {0000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventorys</relationshipLabel>
    <relationshipName>Inventorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Distributor_Type__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Type__c</fullName>
    <formula>if( 
   Distributor_Name__r.Record_type_Name__c = &apos;Super Stockist&apos;,
   Distributor_Name__r.Record_type_Name__c,
   &apos;Direct Distributor&apos;
  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distributor Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product_Rate__c.field-meta.xml
<CustomField>
    <fullName>Product_Rate__c</fullName>
    <label>Product Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Entry__c/Price_Book_Entry__c.object-meta.xml
<CustomObject>
    <label>Price Book Entry</label>
    <nameField>
        <label>Price Book Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Book Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Entry__c/fields/PTD__c.field-meta.xml
<CustomField>
    <fullName>PTD__c</fullName>
    <label>PTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Book_Entry__c/fields/PTSS__c.field-meta.xml
<CustomField>
    <fullName>PTSS__c</fullName>
    <label>PTSS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Book_Entry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Distributor</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Super Stockist</fullName>
            </value>
            <value>
                <fullName>Stash</fullName>
            </value>
            <value>
                <fullName>Retailor</fullName>
                <isActive>false</isActive>
                <label>Retailor</label>
            </value>
            <value>
                <fullName>Under Super Stockist</fullName>
                <isActive>false</isActive>
                <label>Under Super Stockist</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/InventoryPriceUpdateBatch.cls
/*
Created By : Fuzail 
Created Date : 12/01/2026
Batch Class Name : InventoryPriceUpdateBatch
Description : Update the Inventory Product Rate Record based on the Price Book entries and type
*/
public class InventoryPriceUpdateBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Product__c, Distributor_Name__r.Primary_State__c, Distributor_Name__r.Record_type_Name__c FROM Inventory__c WHERE Product__c != NULL AND Distributor_Name__c != NULL AND Product_Rate__c = null'
        );
    }
    public void execute(Database.BatchableContext bc, List<Inventory__c> scope) {
        Set<Id> productIds = new Set<Id>();
        Set<String> states = new Set<String>();
        for (Inventory__c i : scope) {
            productIds.add(i.Product__c);
            if (i.Distributor_Name__r.Primary_State__c != null)
                states.add(i.Distributor_Name__r.Primary_State__c);
        }
        Map<String, Id> priceBookMap = new Map<String, Id>();
        for (Price_Book__c pb : [
            SELECT Id, Name
            FROM Price_Book__c
            WHERE Name IN :states
        ]) {
            priceBookMap.put(pb.Name, pb.Id);
        }
        Map<String, Price_Book_Entry__c> pbeMap = new Map<String, Price_Book_Entry__c>();
        for (Price_Book_Entry__c pbe : [
            SELECT Id,
                   Product__c,
                   Price_Book__c,
                   Type__c,
                   PTD__c,
                   PTSS__c
            FROM Price_Book_Entry__c
            WHERE isActive__c = true
              AND Product__c IN :productIds
              AND Price_Book__c IN :priceBookMap.values()
        ]) {
            pbeMap.put(
                pbe.Product__c + '-' + pbe.Price_Book__c + '-' + pbe.Type__c,
                pbe
            );
        }
        List<Inventory__c> updateList = new List<Inventory__c>();
        for (Inventory__c i : scope) {
            String typeVal;
            if (i.Distributor_Name__r.Record_type_Name__c == 'Super Stockist') {
                typeVal = 'Super Stockist';
            } else {
                //typeVal = String.valueOf(i.Distributor_Name__r.Distributor_Type__c);removed by Fuzail
                typeVal = 'Direct Distributor';
            }
            Id pbId = priceBookMap.get(i.Distributor_Name__r.Primary_State__c);
            if (pbId != null) {
                Price_Book_Entry__c pbe = pbeMap.get(
                    i.Product__c + '-' + pbId + '-' + typeVal
                );
                if (pbe != null) {
                    if (typeVal == 'Super Stockist') {
                        i.Product_Rate__c = pbe.PTSS__c;
                    } else {
                        i.Product_Rate__c = pbe.PTD__c;
                    }
                    updateList.add(i);
                }
            }
        }
        if (!updateList.isEmpty()) {
            update updateList;
        }
    }
    public void finish(Database.BatchableContext bc) {}
}