force-app/main/default/objects/RetailerCodeSetting__c/RetailerCodeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RetailerCodeSetting</label>
</CustomObject>

force-app/main/default/objects/RetailerCodeSetting__c/fields/Latest_Code__c.field-meta.xml
<CustomField>
    <fullName>Latest_Code__c</fullName>
    <label>Latest_Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Tasks (Account)</relationshipLabel>
    <relationshipName>Visit_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed - Order</fullName>
            </value>
            <value>
                <fullName>Completed - No Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Task_Planned_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Planned_Date__c</fullName>
    <label>Task Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateVisitTaskStatusBatchTest.cls
/**
* Test Class  : UpdateVisitTaskStatusBatchTest
* author      : Shyam
* CreatedDate : 22-01-24
* Description : Test class for class 'UpdateVisitTaskStatusBatch'.
                
* */
@isTest
public class UpdateVisitTaskStatusBatchTest {
    @isTest
    static void testBatchExecution() {
        insert new RetailerCodeSetting__c(Name = 'SF', Latest_Code__c = 100);
        
        // Create an Account with Record Type 'Retailer'
        RecordType retailerRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Retailer' LIMIT 1];
        Account retailerAccount = new Account(
            Name = 'Test Retailer Account',
            PAN_Number__c = 'NANAJ4545',
            RecordTypeId = retailerRecordType.Id
        );
        insert retailerAccount;
        
        // Create a Visit associated with the Retailer Account
        Visit__c visit = new Visit__c(
            Account__c = retailerAccount.Id
        );
        insert visit;
        
        // Create test data for Visit_Task__c with Account__c set
        Visit_Task__c task1 = new Visit_Task__c(
            Status__c = 'In Progress',
            Visit__c = visit.Id,
            Account__c = retailerAccount.Id,
            Task_Planned_Date__c = Date.today().addDays(-1)
        );
        Visit_Task__c task2 = new Visit_Task__c(
            Status__c = 'Completed- Order',
            Visit__c = visit.Id,
            Account__c = retailerAccount.Id,
            Task_Planned_Date__c = Date.today().addDays(-1)
        );
        Visit_Task__c task3 = new Visit_Task__c(
            Status__c = 'In Progress',
            Visit__c = visit.Id,
            Account__c = retailerAccount.Id,
            Task_Planned_Date__c = Date.today().addDays(-1)
        );
        insert new List<Visit_Task__c>{task1, task2, task3};
        
        // Verify the records are inserted
        System.assertEquals(3, [SELECT COUNT() FROM Visit_Task__c]);
        
        // Execute the batch
        Test.startTest();
        UpdateVisitTaskStatusBatch batch = new UpdateVisitTaskStatusBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();
        
        // Verify that the status of task1 and task3 is updated to 'Cancelled'
        task1 = [SELECT Status__c FROM Visit_Task__c WHERE Id = :task1.Id];
        task2 = [SELECT Status__c FROM Visit_Task__c WHERE Id = :task2.Id];
        task3 = [SELECT Status__c FROM Visit_Task__c WHERE Id = :task3.Id];
        
        System.assertEquals('Cancelled', task1.Status__c);
    }
}