force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>Asset-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Distributor Name)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Retailer_Account__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountOwnerSyncHandler.cls
/*
 Created By : Fuzail
 Class Name : AccountOwnerSyncHandler
 Description : Updating the Assets OwnerId Related to the Account when changing the Account Owner .
 Created Date : 05/01/2026
*/
public class AccountOwnerSyncHandler {
    public static void syncRetailerAssetOwners(List<Account> newList,Map<Id, Account> oldMap){
        // Null Check 
        if (newList == null || oldMap == null) {
            return;
        }
        // Changing Account Owner 
        Map<Id, Id> accountToOwnerMap = new Map<Id, Id>();
        for (Account acc : newList) {
            if (!oldMap.containsKey(acc.Id)) {
                continue;
            }
            Account oldAcc = oldMap.get(acc.Id);
            // Owner changed
            if (acc.OwnerId != oldAcc.OwnerId) {
                accountToOwnerMap.put(acc.Id, acc.OwnerId);
            }
        }
        if (accountToOwnerMap.isEmpty()) {
            return;
        }
        List<Asset__c> assetsToUpdate = new List<Asset__c>();
		// For Retailers
        List<Asset__c> retailerAssets = [
            SELECT Id, OwnerId, Retailer_Account__c
            FROM Asset__c
            WHERE Retailer_Account__c IN :accountToOwnerMap.keySet()
        ];
        for (Asset__c asset : retailerAssets) {
            asset.OwnerId = accountToOwnerMap.get(asset.Retailer_Account__c);
            asset.Salesman__c = accountToOwnerMap.get(asset.Retailer_Account__c);
            assetsToUpdate.add(asset);
        }
        //For Distributor 
        List<Asset__c> distributorAssets = [
            SELECT Id, OwnerId, Distributor_Name__c, Retailer_Account__c
            FROM Asset__c
            WHERE Distributor_Name__c IN :accountToOwnerMap.keySet()
              AND Retailer_Account__c = NULL
        ];
        for (Asset__c asset : distributorAssets) {
            asset.OwnerId = accountToOwnerMap.get(asset.Distributor_Name__c);
            asset.Salesman__c = accountToOwnerMap.get(asset.Distributor_Name__c);
            assetsToUpdate.add(asset);
        }
        if (!assetsToUpdate.isEmpty()) {
            update assetsToUpdate;
        }
    }
}