force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <label>Competitor Information</label>
    <nameField>
        <displayFormat>Competitor-{0000}</displayFormat>
        <label>Competitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Retailer_Account__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitors Information</relationshipLabel>
    <relationshipName>Competitors_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor__c/fields/Visit_Task__c.field-meta.xml
<CustomField>
    <fullName>Visit_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Task</label>
    <referenceTo>Visit_Task__c</referenceTo>
    <relationshipLabel>Competitors Information</relationshipLabel>
    <relationshipName>Competitors_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Line_Item__c/Competitor_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Competitor Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>CLI number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Line_Item__c/fields/Competitor_Information__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Information__c</fullName>
    <label>Competitor Information</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitor Line Item</relationshipLabel>
    <relationshipName>Competitor_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/Visit_Task__c.object-meta.xml
<CustomObject>
    <label>Visit Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Visit Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Task__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Task__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Tasks</relationshipLabel>
    <relationshipName>Visit_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CompetitorLineItemControllerTest.cls
@isTest
public with sharing class CompetitorLineItemControllerTest {

    /**
     * Test method for createCompetitorWithLineItems
     */
    @isTest
    static void testCreateCompetitorWithLineItems() {
        // Step 1: Create test data
        Account retailer = new Account(Name = 'Test Retailer',PAN_Number__c = 'asd55');
        insert retailer;
        
         Visit__c visit = new Visit__c();
        insert visit;
            
        Visit_Task__c visitTask = new Visit_Task__c(Retailer__c = retailer.Id,Visit__c = visit.Id);
        insert visitTask;
        
        // Create list of LineItemWrapper
        List<CompetitorLineItemController.LineItemWrapper> lineItems = new List<CompetitorLineItemController.LineItemWrapper>();
        
        CompetitorLineItemController.LineItemWrapper item1 = new CompetitorLineItemController.LineItemWrapper();
        item1.brand = 'Brand A';
        item1.quantity = 10;
        item1.description = 'Test description';
        
        CompetitorLineItemController.LineItemWrapper item2 = new CompetitorLineItemController.LineItemWrapper();
        item2.brand = 'Brand B';
        item2.quantity = 5;
        item2.description = 'Another description';
        
        lineItems.add(item1);
        lineItems.add(item2);
        
        Test.startTest();
        // Step 2: Call the method under test
        Competitor__c competitor = CompetitorLineItemController.createCompetitorWithLineItems(visitTask.Id, lineItems);
        Test.stopTest();
        
        // Step 3: Assertions
        System.assertNotEquals(null, competitor, 'Competitor record should be created.');
        System.assertEquals(visitTask.Id, competitor.Visit_Task__c, 'Competitor should be linked to the correct Visit Task.');
        System.assertEquals(retailer.Id, competitor.Retailer_Account__c, 'Competitor should be linked to the correct Retailer.');
        
        // Verify Competitor Line Items
        List<Competitor_Line_Item__c> insertedLineItems = [SELECT Id, Brand__c, Quantity__c, Description__c FROM Competitor_Line_Item__c WHERE Competitor_Information__c = :competitor.Id];
        System.assertEquals(2, insertedLineItems.size(), 'There should be two Competitor Line Items created.');
        
        System.assertEquals('Brand A', insertedLineItems[0].Brand__c, 'First line item brand should be Brand A.');
        System.assertEquals(10, insertedLineItems[0].Quantity__c, 'First line item quantity should be 10.');
        System.assertEquals('Test description', insertedLineItems[0].Description__c, 'First line item description should match.');
    }
}