force-app/main/default/objects/Retailer_Target__c/Retailer_Target__c.object-meta.xml
<CustomObject>
    <label>Retailer Target</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Retailer Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailer Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retailer_Target__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Amount</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retailer_Target__c/fields/MonthYear__c.field-meta.xml
<CustomField>
    <fullName>MonthYear__c</fullName>
    <formula>CASE(MONTH(TODAY()), 
    1, &quot;Jan&quot;, 
    2, &quot;Feb&quot;, 
    3, &quot;Mar&quot;, 
    4, &quot;Apr&quot;, 
    5, &quot;May&quot;, 
    6, &quot;Jun&quot;, 
    7, &quot;Jul&quot;, 
    8, &quot;Aug&quot;, 
    9, &quot;Sep&quot;, 
    10, &quot;Oct&quot;, 
    11, &quot;Nov&quot;, 
    12, &quot;Dec&quot;, 
    &quot;&quot;) + &quot; &quot; + TEXT(YEAR(TODAY()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retailer_Target__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <label>Retailer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Retailer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Retailer Targets</relationshipLabel>
    <relationshipName>Retailer_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RetailerTargetTriggerHandler.cls
/**
* Class Name  : OrderProductController
* Test Class  : OrderProductControllerTest
* author      : Ashwini
* CreatedDate : 25-12-24
* Description : Created to update Monthly target value on account
* */
public without sharing class RetailerTargetTriggerHandler {
    //This method is to updateAmountOnAccount
    public static void updateAmountOnAccount(List<Retailer_Target__c> targetList) {
        Set<Id> accountIds = extractAccountIds(targetList);
        
        if (accountIds.isEmpty()) {
            return;
        }
        
        List<Retailer_Target__c> retList = queryRetailerTargets(accountIds);
        
        String currentMonth = getCurrentMonth();
        
        Map<Id, Decimal> accountMonthlyTargets = processTargetRecords(retList, currentMonth);
        
        List<Account> accountsToUpdate = prepareAccountsToUpdate(accountIds, accountMonthlyTargets);
        
        updateAccounts(accountsToUpdate);
    }
    //This method is to extractAccountIds
    
    private static Set<Id> extractAccountIds(List<Retailer_Target__c> targetList) {
        Set<Id> accountIds = new Set<Id>();
        for (Retailer_Target__c ret : targetList) {
            if (ret.Retailer__c != null) {
                accountIds.add(ret.Retailer__c);
            }
        }
        return accountIds;
    }
    //This method is to queryRetailerTargets
    
    private static List<Retailer_Target__c> queryRetailerTargets(Set<Id> accountIds) {
        return [
            SELECT Id, Retailer__c, Amount__c, MonthYear__c
            FROM Retailer_Target__c
            WHERE Retailer__c IN :accountIds
        ];
    }
    //This method is to getCurrentMonth
    private static String getCurrentMonth() {
        return DateTime.now().format('MMM yyyy');
    }
    //This method is to processTargetRecords
    
    private static Map<Id, Decimal> processTargetRecords(List<Retailer_Target__c> retList, String currentMonth) {
        Map<Id, Decimal> accountMonthlyTargets = new Map<Id, Decimal>();
        for (Retailer_Target__c ret : retList) {
            if (ret.MonthYear__c == currentMonth && ret.Amount__c != null && ret.Amount__c != '') {
                try {
                    Decimal amountDecimal = Decimal.valueOf(ret.Amount__c);
                    accountMonthlyTargets.put(ret.Retailer__c, amountDecimal);
                } catch (Exception e) {
                    System.debug('Error converting Amount__c to Decimal: ' + e.getMessage());
                }
            }
        }
        return accountMonthlyTargets;
    }
    //This method is to prepareAccountsToUpdate
    
    private static List<Account> prepareAccountsToUpdate(Set<Id> accountIds, Map<Id, Decimal> accountMonthlyTargets) {
        List<Account> accountsToUpdate = new List<Account>();
        for (Id accountId : accountIds) {
            if (accountMonthlyTargets.containsKey(accountId)) {
                Account acc = new Account(Id = accountId);
                acc.Monthly_Target__c = accountMonthlyTargets.get(accountId);
                accountsToUpdate.add(acc);
            }
        }
        return accountsToUpdate;
    }
    //This method is to updateAccounts
    
    private static void updateAccounts(List<Account> accountsToUpdate) {
        if (!accountsToUpdate.isEmpty()) {
            try {
                update accountsToUpdate;
            } catch (DmlException dmlEx) {
                // Log the error for debugging and visibility
                System.debug('Error updating accounts: ' + dmlEx.getMessage());
            }
        }
    }
}