force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Value__c</fullName>
    <label>Total Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Secondary_Order.recordType-meta.xml
<RecordType>
    <fullName>Secondary_Order</fullName>
    <active>true</active>
    <label>Secondary Order</label>
</RecordType>

force-app/main/default/objects/Sales_Target__c/Sales_Target__c.object-meta.xml
<CustomObject>
    <label>Sales Performance</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Sales Performance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/New_Outlet_Opened_Actual__c.field-meta.xml
<CustomField>
    <fullName>New_Outlet_Opened_Actual__c</fullName>
    <label>New Outlet Opened Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Number_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Month__c</fullName>
    <label>Number of Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Productive_Calls_Actual__c.field-meta.xml
<CustomField>
    <fullName>Productive_Calls_Actual__c</fullName>
    <label>Productive Calls Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerExecutionController__c/TriggerExecutionController__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TriggerExecutionController</label>
</CustomObject>

force-app/main/default/classes/UpdateSalesPerformanceProducCallsTest.cls
@isTest
public class UpdateSalesPerformanceProducCallsTest {
    @isTest
    static void testUpdateSalesPerformance() {
        
        Id secondaryInvoiceRT = [SELECT Id FROM RecordType WHERE SObjectType = 'Order__c' AND DeveloperName = 'Secondary_Order' LIMIT 1].Id;
        
        User accountOwner = [SELECT Id, UserRoleId FROM User WHERE IsActive = TRUE AND UserRoleId != null LIMIT 1];
        
        Id retailerRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Retailer' LIMIT 1].Id;
        
        Account retailerAccount = new Account();
        retailerAccount.RecordTypeId = retailerRecordType;
        retailerAccount.Name = 'Retailer Account';
        retailerAccount.OwnerId = accountOwner.Id;
        insert retailerAccount;
        
        Sales_Target__c salesTarget = new Sales_Target__c();
        salesTarget.OwnerId = accountOwner.Id;
        salesTarget.Assigned_To__c = accountOwner.Id;
        salesTarget.Number_of_Month__c = Date.today().month();
        salesTarget.Productive_Calls_Actual__c = 0;
        salesTarget.New_Outlet_Opened_Actual__c = 0;
        insert salesTarget;
        
        TriggerExecutionController__c tt = new TriggerExecutionController__c();
        tt.Name = 'OrderTrigger';
        tt.Is_Active__c = true;
        insert tt;
        
        Order__c order = new Order__c();
        order.Account__c = retailerAccount.Id;
        order.Total_Order_Value__c = 10000;
        order.RecordTypeId = secondaryInvoiceRT;
        insert order;
        
        
        order = [SELECT Id,RecordTypeId,Account__c,CreatedDate,Total_Order_Value__c FROM Order__c WHERE Id = :order.Id LIMIT 1];
        
        Test.setCreatedDate(order.Id, DateTime.newInstance(2025, 7, 10, 0, 0, 0));
        
        Test.startTest();
        UpdateSalesPerformanceProducCallsActual.updateSalesPerformance(new List<Order__c>{order});
        Test.stopTest();
        
    }
    
    @isTest
    static void testOrderUnDelete() {
        
        Id secondaryInvoiceRT = [SELECT Id FROM RecordType WHERE SObjectType = 'Order__c' AND DeveloperName = 'Secondary_Order' LIMIT 1].Id;
        
        User accountOwner = [SELECT Id, UserRoleId FROM User WHERE IsActive = TRUE AND UserRoleId != null LIMIT 1];
        
        Id retailerRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Retailer' LIMIT 1].Id;
        
        Account retailerAccount = new Account();
        retailerAccount.RecordTypeId = retailerRecordType;
        retailerAccount.Name = 'Retailer Account';
        retailerAccount.OwnerId = accountOwner.Id;
        insert retailerAccount;
        
        Sales_Target__c salesTarget = new Sales_Target__c();
        salesTarget.OwnerId = accountOwner.Id;
        salesTarget.Assigned_To__c = accountOwner.Id;
        salesTarget.Number_of_Month__c = Date.today().month();
        salesTarget.Productive_Calls_Actual__c = 0;
        salesTarget.New_Outlet_Opened_Actual__c = 0;
        insert salesTarget;
        
        TriggerExecutionController__c tt = new TriggerExecutionController__c();
        tt.Name = 'OrderTrigger';
        tt.Is_Active__c = true;
        insert tt;
        
        Order__c order = new Order__c();
        order.Account__c = retailerAccount.Id;
        order.Total_Order_Value__c = 10000;
        order.RecordTypeId = secondaryInvoiceRT;
        insert order;
        
        
        order = [SELECT Id,RecordTypeId,Account__c,CreatedDate,Total_Order_Value__c FROM Order__c WHERE Id = :order.Id LIMIT 1];
        
        Test.setCreatedDate(order.Id, DateTime.newInstance(2025, 7, 10, 0, 0, 0));        
        
        List<Order__c> orders = [SELECT Id, Status__c FROM Order__c Limit 1];
        
        for (Order__c ord : orders) {
            ord.Status__c = 'Order Placed';
        }
        
        delete orders;
        
        Test.startTest();
        Undelete orders;
        Test.stopTest();
        
    }
}