force-app/main/default/objects/Casual_Leaves__c/Casual_Leaves__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to update the Leave allowance on yearly basis</description>
    <label>Casual Leave</label>
</CustomObject>

force-app/main/default/objects/Casual_Leaves__c/fields/Total_Casual_Leave__c.field-meta.xml
<CustomField>
    <fullName>Total_Casual_Leave__c</fullName>
    <label>Total Casual Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/Employee_Leave_Allowance__c.object-meta.xml
<CustomObject>
    <label>Employee Leave Allowance</label>
    <nameField>
        <label>Employee Leave Allowances Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Leave Allowance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Total_Casual_Leave__c.field-meta.xml
<CustomField>
    <fullName>Total_Casual_Leave__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Total Casual Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Total_Maternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>Total_Maternity_Leave__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Total Maternity Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Total_Sick_Leave__c.field-meta.xml
<CustomField>
    <fullName>Total_Sick_Leave__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Total Sick Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Used_Casual_Leave__c.field-meta.xml
<CustomField>
    <fullName>Used_Casual_Leave__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Used Casual Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Used_Earned_Leave__c.field-meta.xml
<CustomField>
    <fullName>Used_Earned_Leave__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Used Earned Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Used_Sick_Leave__c.field-meta.xml
<CustomField>
    <fullName>Used_Sick_Leave__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Used Sick Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Allowance__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(CreatedDate)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Maternity_Leave__c/Maternity_Leave__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To update the employee leave allowance</description>
    <label>Maternity Leave</label>
</CustomObject>

force-app/main/default/objects/Maternity_Leave__c/fields/Total_Maternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>Total_Maternity_Leave__c</fullName>
    <label>Total Maternity Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sick_Leave__c/Sick_Leave__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To update the employee leave allowance</description>
    <label>Sick Leave</label>
</CustomObject>

force-app/main/default/objects/Sick_Leave__c/fields/Total_Sick_Leave__c.field-meta.xml
<CustomField>
    <fullName>Total_Sick_Leave__c</fullName>
    <label>Total Sick Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateEmployeeLeaveAllowance.cls
/**
* Class Name  : CreateEmployeeLeaveAllowance
* Test Class  : TestCreateEmployeeLeaveAllowance
* author      : Mirza
* CreatedDate : 23-01-25
* Description : This is to create all "Employee Leave Allowance" record on yearly basis (first of Jan for every Year).
* */
public class CreateEmployeeLeaveAllowance {
    
    public static void employeeLeaveAllowanceMethod() {
        // Retrieve Custom Settings values
        List<User> userList = [SELECT Name, Id,Employee_Role__c FROM User WHERE IsActive = true AND (Employee_Role__c IN ('SO', 'SSO', 'ASM' , 'RSM' , 'ZSM' , 'PSR'))];
        
        Casual_Leaves__c customCasualLeaves = [SELECT Total_Casual_Leave__c FROM Casual_Leaves__c WHERE Name = 'Casual Leave Value' LIMIT 1];
        Sick_Leave__c customSickLeaves = [SELECT Total_Sick_Leave__c FROM Sick_Leave__c WHERE Name = 'Sick Leave Value' LIMIT 1];
        Maternity_Leave__c customMaternityLeaves = [SELECT Total_Maternity_Leave__c FROM Maternity_Leave__c WHERE Name = 'Maternity Leave Value' LIMIT 1];
        Map <Id,User> userMap = new Map <Id, User>([SELECT Name, Email FROM User]);
        Set<Id> userIds = new Set<Id>();
        if(userList.size()>0){
            for (User userId : userList) {
                userIds.add(userId.Id);
            }
        }
        System.debug('Set of user Id: '+ userIds);
        
        String currentYear = String.ValueOf(System.today().year());
        Map<Id, Employee_Leave_Allowance__c> existingAllowances = new Map<Id, Employee_Leave_Allowance__c>();
        for (Employee_Leave_Allowance__c allowance : 
             [SELECT Id, User__c FROM Employee_Leave_Allowance__c WHERE User__c IN :userIds AND Year__c = :currentYear]) {
             existingAllowances.put(allowance.User__c, allowance);
        }
        System.debug('Employee leave allowance which already exists: '+ existingAllowances);
        
        List<Employee_Leave_Allowance__c> newLeaveRecords = new List<Employee_Leave_Allowance__c>();
        Employee_Leave_Allowance__c newAllowance;
        for (Id userRecord : userIds) {
            if (existingAllowances.containsKey(userRecord)) { 
                continue;
            }
            newAllowance = new Employee_Leave_Allowance__c();
            newAllowance.User__c = userRecord; // Maintain the same User
            newAllowance.OwnerId = userRecord; // Maintain the same User
            newAllowance.Total_Casual_Leave__c = customCasualLeaves.Total_Casual_Leave__c;
            newAllowance.Total_Sick_Leave__c = customSickLeaves.Total_Sick_Leave__c;
            newAllowance.Total_Maternity_Leave__c = customMaternityLeaves.Total_Maternity_Leave__c;
            newAllowance.Used_Casual_Leave__c = 0;
            newAllowance.Used_Sick_Leave__c = 0;
            newAllowance.Used_Earned_Leave__c = 0;
            newAllowance.Name = String.valueOf(Date.today().year()) + ' ' + userMap.get(userRecord).Name + ' - Leave Allowance';
            
            newLeaveRecords.add(newAllowance);
        }
        
        System.debug('newLeaveRecords: '+ newLeaveRecords);
        if (!newLeaveRecords.isEmpty()) {
            insert newLeaveRecords;
        }
    }
}